In [1]:
import pandas as pd

In [4]:
#Read excel data
df = pd.read_excel(r"C:\Users\Ridhi Rathore\Downloads\pandas_data_selection_filtering_practice.xlsx")
df

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
1         1002    Diya         HR   48000           1
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2
8         1009   Arjun         IT   75000           6
9         1010   Kiara      Sales   50000           2

In [6]:
#Select name columns
df["Name"]

0     Aarav
1      Diya
2     Rohan
3     Anaya
4    Vivaan
5    Ishita
6    Aditya
7      Myra
8     Arjun
9     Kiara
Name: Name, dtype: object

In [7]:
#Select 2 columns name and salary 
df[["Name","Salary"]]

     Name  Salary
0   Aarav   55000
1    Diya   48000
2   Rohan   62000
3   Anaya   70000
4  Vivaan   45000
5  Ishita   52000
6  Aditya   68000
7    Myra   58000
8   Arjun   75000
9   Kiara   50000

In [38]:
#Select row and colums Employe_id 1009 
df.loc[8]

Employee_ID     1009
Name           Arjun
Department        IT
Salary         75000
Experience         6
Name: 8, dtype: object

In [37]:
#Select  Employe_id 1004 only get salary columns
df.loc[3,["Salary"]]

Salary    70000
Name: 3, dtype: object

In [39]:
#Select first row use iloc
df.iloc[0]

Employee_ID     1001
Name           Aarav
Department        IT
Salary         55000
Experience         2
Name: 0, dtype: object

In [40]:
#Select 5th row and only Name column
df.iloc[5,1]

'Ishita'

In [43]:
#use loc select employe_id 1003 and 1007 and column only name and salary 
df.loc[[2,6],["Employee_ID","Name","Salary"]]

   Employee_ID    Name  Salary
2         1003   Rohan   62000
6         1007  Aditya   68000

In [46]:
#(at) use Find the salary of employee_id 1009
df.at[8,"Salary"]

np.int64(75000)

In [48]:
#(iat) Find the salary of the 3rd employe 
df.iat[2,3]

np.int64(62000)

In [52]:
#Print 6 employe details
df.loc[0:5]

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
1         1002    Diya         HR   48000           1
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3

#Filtering with conditions

In [61]:
df

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
1         1002    Diya         HR   48000           1
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2
8         1009   Arjun         IT   75000           6
9         1010   Kiara      Sales   50000           2

In [62]:
#Whose salary is greaterthan 60000
df[df["Salary"] > 60000]

   Employee_ID    Name Department  Salary  Experience
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
6         1007  Aditya    Finance   68000           4
8         1009   Arjun         IT   75000           6

In [66]:
#who employe work IT department 
df[df["Department"] == "IT"]

   Employee_ID   Name Department  Salary  Experience
0         1001  Aarav         IT   55000           2
3         1004  Anaya         IT   70000           5
8         1009  Arjun         IT   75000           6

In [71]:
#Whose employees 3 year experience
df[df["Experience"] >=3]

   Employee_ID    Name Department  Salary  Experience
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
8         1009   Arjun         IT   75000           6

In [72]:
#Whose salary less than 50000
df[df["Salary"] < 50000]

   Employee_ID    Name Department  Salary  Experience
1         1002    Diya         HR   48000           1
4         1005  Vivaan      Sales   45000           1

In [76]:
#Who work in the IT Department and salary is 60000 up
df[(df["Department"] == "IT") & (df["Salary"] >= 60000)]

   Employee_ID   Name Department  Salary  Experience
3         1004  Anaya         IT   70000           5
8         1009  Arjun         IT   75000           6

In [79]:
#Who work in the HR or Sales department 
df[(df["Department"] == "HR") | (df["Department"] == "Sales")]

   Employee_ID    Name Department  Salary  Experience
1         1002    Diya         HR   48000           1
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3
9         1010   Kiara      Sales   50000           2

In [82]:
#Who have more than 2 year experience and salary 55000 up 
df[(df["Experience"] >= 2) & (df["Salary"] >= 55000)]

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2
8         1009   Arjun         IT   75000           6

In [83]:
#Who work in the IT department and have more than 3 years of experience
df[(df["Department"] == "IT" ) & (df["Experience"] >= 3)]

   Employee_ID   Name Department  Salary  Experience
3         1004  Anaya         IT   70000           5
8         1009  Arjun         IT   75000           6

In [84]:
#Whose salary is between 50000 and 70000
df[(df["Salary"] > 50000) & (df["Salary"] < 70000)]

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
2         1003   Rohan    Finance   62000           4
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2

In [5]:
#Who work in the Finance department and salary is 60000 up
df[(df["Department"] == "Finance") & (df["Salary"] >= 60000)]

   Employee_ID    Name Department  Salary  Experience
2         1003   Rohan    Finance   62000           4
6         1007  Aditya    Finance   68000           4

#New_Data

In [6]:
df1 = pd.read_excel(r"C:\Users\Ridhi Rathore\Downloads\Power_Query_Practice_Data.xlsx")
df1

,OrderID,Date,Customer,City,Category,Product,Qty,Price,Discount,Payment
0,1001,2026-01-05,Amit,Ahmedabad,Mobile,Samsung A56,2,25000,10,UPI
1,1002,2026-01-06,Neha,Surat,Laptop,HP 15,1,52000,5,Card
2,1003,2026-01-07,Raj,Vadodara,Accessory,Mouse,3,800,0,Cash
3,1004,2026-01-08,Pooja,Rajkot,Mobile,iPhone 15,1,70000,8,Card
4,1005,2026-01-09,Karan,Ahmedabad,Tablet,iPad,2,35000,12,UPI
5,1006,2026-01-10,Meera,Surat,Laptop,Lenovo,1,48000,7,EMI
6,1007,2026-01-11,Vikas,Bhavnagar,Accessory,Keyboard,4,1200,5,Cash
7,1008,2026-01-12,Riya,Ahmedabad,Mobile,OnePlus,2,30000,10,UPI
8,1009,2026-01-13,Arjun,Surat,Tablet,Samsung Tab,1,28000,15,Card
9,1010,2026-01-14,Nisha,Rajkot,Accessory,Headphones,5,1500,0,Cash

In [7]:
#Select only Category columns
df1["Category"]

0       Mobile
1       Laptop
2    Accessory
3       Mobile
4       Tablet
5       Laptop
6    Accessory
7       Mobile
8       Tablet
9    Accessory
Name: Category, dtype: object

In [8]:
#Select 4 columns Order-id,Date,name,product 
df1[["OrderID","Date","Customer","Product"]]

   OrderID        Date Customer      Product
0     1001  2026-01-05     Amit  Samsung A56
1     1002  2026-01-06     Neha        HP 15
2     1003  2026-01-07      Raj        Mouse
3     1004  2026-01-08    Pooja    iPhone 15
4     1005  2026-01-09    Karan         iPad
5     1006  2026-01-10    Meera       Lenovo
6     1007  2026-01-11    Vikas     Keyboard
7     1008  2026-01-12     Riya      OnePlus
8     1009  2026-01-13    Arjun  Samsung Tab
9     1010  2026-01-14    Nisha   Headphones

In [14]:
df1.loc[0]

OrderID            1001
Date         2026-01-05
Customer           Amit
City          Ahmedabad
Category         Mobile
Product     Samsung A56
Qty                   2
Price             25000
Discount             10
Payment             UPI
Name: 0, dtype: object

In [15]:
df1.loc[0:5,["Customer","Product"]]

  Customer      Product
0     Amit  Samsung A56
1     Neha        HP 15
2      Raj        Mouse
3    Pooja    iPhone 15
4    Karan         iPad
5    Meera       Lenovo

In [16]:
df1.iloc[0:5,0:6]

   OrderID        Date Customer       City   Category      Product
0     1001  2026-01-05     Amit  Ahmedabad     Mobile  Samsung A56
1     1002  2026-01-06     Neha      Surat     Laptop        HP 15
2     1003  2026-01-07      Raj   Vadodara  Accessory        Mouse
3     1004  2026-01-08    Pooja     Rajkot     Mobile    iPhone 15
4     1005  2026-01-09    Karan  Ahmedabad     Tablet         iPad

In [17]:
#Only orderid Date customer product columns access use iloc
df1.iloc[0:5,[0,1,2,5]]

   OrderID        Date Customer      Product
0     1001  2026-01-05     Amit  Samsung A56
1     1002  2026-01-06     Neha        HP 15
2     1003  2026-01-07      Raj        Mouse
3     1004  2026-01-08    Pooja    iPhone 15
4     1005  2026-01-09    Karan         iPad

In [21]:
#select only customer name  use at 
df1.at[0,"Customer"]
df1.at[4,"Product"]

'iPad'

In [23]:
#use iat access raj name 
df1.iat[2,2]

'Raj'

In [24]:
df1

,OrderID,Date,Customer,City,Category,Product,Qty,Price,Discount,Payment
0,1001,2026-01-05,Amit,Ahmedabad,Mobile,Samsung A56,2,25000,10,UPI
1,1002,2026-01-06,Neha,Surat,Laptop,HP 15,1,52000,5,Card
2,1003,2026-01-07,Raj,Vadodara,Accessory,Mouse,3,800,0,Cash
3,1004,2026-01-08,Pooja,Rajkot,Mobile,iPhone 15,1,70000,8,Card
4,1005,2026-01-09,Karan,Ahmedabad,Tablet,iPad,2,35000,12,UPI
5,1006,2026-01-10,Meera,Surat,Laptop,Lenovo,1,48000,7,EMI
6,1007,2026-01-11,Vikas,Bhavnagar,Accessory,Keyboard,4,1200,5,Cash
7,1008,2026-01-12,Riya,Ahmedabad,Mobile,OnePlus,2,30000,10,UPI
8,1009,2026-01-13,Arjun,Surat,Tablet,Samsung Tab,1,28000,15,Card
9,1010,2026-01-14,Nisha,Rajkot,Accessory,Headphones,5,1500,0,Cash

In [26]:
#Filtering 
df1[df1["Price"] >= 50000]

,OrderID,Date,Customer,City,Category,Product,Qty,Price,Discount,Payment
1,1002,2026-01-06,Neha,Surat,Laptop,HP 15,1,52000,5,Card
3,1004,2026-01-08,Pooja,Rajkot,Mobile,iPhone 15,1,70000,8,Card