In [2]:
import pandas as pd
import numpy as np

In [3]:
#Read excel data
df = pd.read_excel(r"C:\Users\Ridhi Rathore\Downloads\pandas_data_selection_filtering_practice.xlsx")
df

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
1         1002    Diya         HR   48000           1
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2
8         1009   Arjun         IT   75000           6
9         1010   Kiara      Sales   50000           2

In [4]:
#Select name columns
df["Name"]

0     Aarav
1      Diya
2     Rohan
3     Anaya
4    Vivaan
5    Ishita
6    Aditya
7      Myra
8     Arjun
9     Kiara
Name: Name, dtype: object

In [5]:
#Select 2 columns name and salary 
df[["Name","Salary"]]

     Name  Salary
0   Aarav   55000
1    Diya   48000
2   Rohan   62000
3   Anaya   70000
4  Vivaan   45000
5  Ishita   52000
6  Aditya   68000
7    Myra   58000
8   Arjun   75000
9   Kiara   50000

In [6]:
#Select row and colums Employe_id 1009 
df.loc[8]

Employee_ID     1009
Name           Arjun
Department        IT
Salary         75000
Experience         6
Name: 8, dtype: object

In [7]:
#Select  Employe_id 1004 only get salary columns
df.loc[3,["Salary"]]

Salary    70000
Name: 3, dtype: object

In [8]:
#Select first row use iloc
df.iloc[0]

Employee_ID     1001
Name           Aarav
Department        IT
Salary         55000
Experience         2
Name: 0, dtype: object

In [9]:
#Select 5th row and only Name column
df.iloc[5,1]

'Ishita'

In [10]:
#use loc select employe_id 1003 and 1007 and column only name and salary 
df.loc[[2,6],["Employee_ID","Name","Salary"]]

   Employee_ID    Name  Salary
2         1003   Rohan   62000
6         1007  Aditya   68000

In [11]:
#(at) use Find the salary of employee_id 1009
df.at[8,"Salary"]

np.int64(75000)

In [12]:
#(iat) Find the salary of the 3rd employe 
df.iat[2,3]

np.int64(62000)

In [13]:
#Print 6 employe details
df.loc[0:5]

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
1         1002    Diya         HR   48000           1
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3

#Filtering with conditions

In [14]:
df

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
1         1002    Diya         HR   48000           1
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2
8         1009   Arjun         IT   75000           6
9         1010   Kiara      Sales   50000           2

In [15]:
#Whose salary is greaterthan 60000
df[df["Salary"] > 60000]

   Employee_ID    Name Department  Salary  Experience
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
6         1007  Aditya    Finance   68000           4
8         1009   Arjun         IT   75000           6

In [16]:
#who employe work IT department 
df[df["Department"] == "IT"]

   Employee_ID   Name Department  Salary  Experience
0         1001  Aarav         IT   55000           2
3         1004  Anaya         IT   70000           5
8         1009  Arjun         IT   75000           6

In [17]:
#Whose employees 3 year experience
df[df["Experience"] >=3]

   Employee_ID    Name Department  Salary  Experience
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
8         1009   Arjun         IT   75000           6

In [18]:
#Whose salary less than 50000
df[df["Salary"] < 50000]

   Employee_ID    Name Department  Salary  Experience
1         1002    Diya         HR   48000           1
4         1005  Vivaan      Sales   45000           1

In [19]:
#Who work in the IT Department and salary is 60000 up
df[(df["Department"] == "IT") & (df["Salary"] >= 60000)]

   Employee_ID   Name Department  Salary  Experience
3         1004  Anaya         IT   70000           5
8         1009  Arjun         IT   75000           6

In [20]:
#Who work in the HR or Sales department 
df[(df["Department"] == "HR") | (df["Department"] == "Sales")]

   Employee_ID    Name Department  Salary  Experience
1         1002    Diya         HR   48000           1
4         1005  Vivaan      Sales   45000           1
5         1006  Ishita         HR   52000           3
9         1010   Kiara      Sales   50000           2

In [21]:
#Who have more than 2 year experience and salary 55000 up 
df[(df["Experience"] >= 2) & (df["Salary"] >= 55000)]

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
2         1003   Rohan    Finance   62000           4
3         1004   Anaya         IT   70000           5
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2
8         1009   Arjun         IT   75000           6

In [22]:
#Who work in the IT department and have more than 3 years of experience
df[(df["Department"] == "IT" ) & (df["Experience"] >= 3)]

   Employee_ID   Name Department  Salary  Experience
3         1004  Anaya         IT   70000           5
8         1009  Arjun         IT   75000           6

In [23]:
#Whose salary is between 50000 and 70000
df[(df["Salary"] > 50000) & (df["Salary"] < 70000)]

   Employee_ID    Name Department  Salary  Experience
0         1001   Aarav         IT   55000           2
2         1003   Rohan    Finance   62000           4
5         1006  Ishita         HR   52000           3
6         1007  Aditya    Finance   68000           4
7         1008    Myra  Marketing   58000           2

In [24]:
#Who work in the Finance department and salary is 60000 up
df[(df["Department"] == "Finance") & (df["Salary"] >= 60000)]

   Employee_ID    Name Department  Salary  Experience
2         1003   Rohan    Finance   62000           4
6         1007  Aditya    Finance   68000           4

#New_Data

In [25]:
df1 = pd.read_excel(r"C:\Users\Ridhi Rathore\Downloads\Power_Query_Practice_Data.xlsx")
df1

,OrderID,Date,Customer,City,Category,Product,Qty,Price,Discount,Payment
0,1001,2026-01-05,Amit,Ahmedabad,Mobile,Samsung A56,2,25000,10,UPI
1,1002,2026-01-06,Neha,Surat,Laptop,HP 15,1,52000,5,Card
2,1003,2026-01-07,Raj,Vadodara,Accessory,Mouse,3,800,0,Cash
3,1004,2026-01-08,Pooja,Rajkot,Mobile,iPhone 15,1,70000,8,Card
4,1005,2026-01-09,Karan,Ahmedabad,Tablet,iPad,2,35000,12,UPI
5,1006,2026-01-10,Meera,Surat,Laptop,Lenovo,1,48000,7,EMI
6,1007,2026-01-11,Vikas,Bhavnagar,Accessory,Keyboard,4,1200,5,Cash
7,1008,2026-01-12,Riya,Ahmedabad,Mobile,OnePlus,2,30000,10,UPI
8,1009,2026-01-13,Arjun,Surat,Tablet,Samsung Tab,1,28000,15,Card
9,1010,2026-01-14,Nisha,Rajkot,Accessory,Headphones,5,1500,0,Cash

In [26]:
#Select only Category columns
df1["Category"]

0       Mobile
1       Laptop
2    Accessory
3       Mobile
4       Tablet
5       Laptop
6    Accessory
7       Mobile
8       Tablet
9    Accessory
Name: Category, dtype: object

In [27]:
#Select 4 columns Order-id,Date,name,product 
df1[["OrderID","Date","Customer","Product"]]

   OrderID        Date Customer      Product
0     1001  2026-01-05     Amit  Samsung A56
1     1002  2026-01-06     Neha        HP 15
2     1003  2026-01-07      Raj        Mouse
3     1004  2026-01-08    Pooja    iPhone 15
4     1005  2026-01-09    Karan         iPad
5     1006  2026-01-10    Meera       Lenovo
6     1007  2026-01-11    Vikas     Keyboard
7     1008  2026-01-12     Riya      OnePlus
8     1009  2026-01-13    Arjun  Samsung Tab
9     1010  2026-01-14    Nisha   Headphones

In [28]:
df1.loc[0]

OrderID            1001
Date         2026-01-05
Customer           Amit
City          Ahmedabad
Category         Mobile
Product     Samsung A56
Qty                   2
Price             25000
Discount             10
Payment             UPI
Name: 0, dtype: object

In [29]:
df1.loc[0:5,["Customer","Product"]]

  Customer      Product
0     Amit  Samsung A56
1     Neha        HP 15
2      Raj        Mouse
3    Pooja    iPhone 15
4    Karan         iPad
5    Meera       Lenovo

In [30]:
df1.iloc[0:5,0:6]

   OrderID        Date Customer       City   Category      Product
0     1001  2026-01-05     Amit  Ahmedabad     Mobile  Samsung A56
1     1002  2026-01-06     Neha      Surat     Laptop        HP 15
2     1003  2026-01-07      Raj   Vadodara  Accessory        Mouse
3     1004  2026-01-08    Pooja     Rajkot     Mobile    iPhone 15
4     1005  2026-01-09    Karan  Ahmedabad     Tablet         iPad

In [31]:
#Only orderid Date customer product columns access use iloc
df1.iloc[0:5,[0,1,2,5]]

   OrderID        Date Customer      Product
0     1001  2026-01-05     Amit  Samsung A56
1     1002  2026-01-06     Neha        HP 15
2     1003  2026-01-07      Raj        Mouse
3     1004  2026-01-08    Pooja    iPhone 15
4     1005  2026-01-09    Karan         iPad

In [32]:
#select only customer name  use at 
df1.at[0,"Customer"]
df1.at[4,"Product"]

'iPad'

In [33]:
#use iat access raj name 
df1.iat[2,2]

'Raj'

In [34]:
df1

,OrderID,Date,Customer,City,Category,Product,Qty,Price,Discount,Payment
0,1001,2026-01-05,Amit,Ahmedabad,Mobile,Samsung A56,2,25000,10,UPI
1,1002,2026-01-06,Neha,Surat,Laptop,HP 15,1,52000,5,Card
2,1003,2026-01-07,Raj,Vadodara,Accessory,Mouse,3,800,0,Cash
3,1004,2026-01-08,Pooja,Rajkot,Mobile,iPhone 15,1,70000,8,Card
4,1005,2026-01-09,Karan,Ahmedabad,Tablet,iPad,2,35000,12,UPI
5,1006,2026-01-10,Meera,Surat,Laptop,Lenovo,1,48000,7,EMI
6,1007,2026-01-11,Vikas,Bhavnagar,Accessory,Keyboard,4,1200,5,Cash
7,1008,2026-01-12,Riya,Ahmedabad,Mobile,OnePlus,2,30000,10,UPI
8,1009,2026-01-13,Arjun,Surat,Tablet,Samsung Tab,1,28000,15,Card
9,1010,2026-01-14,Nisha,Rajkot,Accessory,Headphones,5,1500,0,Cash

#Revison

In [35]:
df = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\small_sales_eda_practice.csv")
df

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
1,102,Priya,Mumbai,Clothing,Jeans,2,3600,4.0
2,103,Amit,Delhi,Grocery,Rice,5,4500,3.5
3,104,Neha,Ahmedabad,Electronics,Mouse,3,2400,4.2
4,105,Karan,Surat,Clothing,T-Shirt,4,2800,4.8
5,106,Riya,Mumbai,Electronics,Keyboard,2,3000,4.1
6,107,Mohit,Delhi,Grocery,Oil,3,4500,3.8
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
8,109,Raj,Surat,Electronics,Headphones,2,4400,4.3
9,110,Simran,Mumbai,Clothing,Jeans,3,5400,3.9
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
11,112,Meena,Delhi,Furniture,Table,1,6500,4.0
12,113,Arjun,Surat,Grocery,Rice,6,5400,3.6
13,114,Pooja,Ahmedabad,Clothing,T-Shirt,5,3500,4.4
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

#Data selection

In [36]:
#Select the customer name column
df["Customer"]

0      Rahul
1      Priya
2       Amit
3       Neha
4      Karan
5       Riya
6      Mohit
7     Anjali
8        Raj
9     Simran
10       Dev
11     Meena
12     Arjun
13     Pooja
14     Rohan
Name: Customer, dtype: object

In [37]:
#Select customer name and city 
df[["Customer","City"]]

   Customer       City
0     Rahul  Ahmedabad
1     Priya     Mumbai
2      Amit      Delhi
3      Neha  Ahmedabad
4     Karan      Surat
5      Riya     Mumbai
6     Mohit      Delhi
7    Anjali  Ahmedabad
8       Raj      Surat
9    Simran     Mumbai
10      Dev  Ahmedabad
11    Meena      Delhi
12    Arjun      Surat
13    Pooja  Ahmedabad
14    Rohan     Mumbai

In [38]:
#Select product,quentity,sales columns
df[["Product","Quantity","Sales"]]

       Product  Quantity   Sales
0       Laptop         1   55000
1        Jeans         2    3600
2         Rice         5    4500
3        Mouse         3    2400
4      T-Shirt         4    2800
5     Keyboard         2    3000
6          Oil         3    4500
7        Chair         4   10000
8   Headphones         2    4400
9        Jeans         3    5400
10      Laptop         2  110000
11       Table         1    6500
12        Rice         6    5400
13     T-Shirt         5    3500
14      Tablet         2   50000

#Selecting rows

In [39]:
#Select the customer at index 3
df.loc[3]

Order_ID            104
Customer           Neha
City          Ahmedabad
Category    Electronics
Product           Mouse
Quantity              3
Sales              2400
Rating              4.2
Name: 3, dtype: object

In [40]:
#Select first 5 rows only customer name and sales 
df.loc[0:4,["Customer","Sales"]]

  Customer  Sales
0    Rahul  55000
1    Priya   3600
2     Amit   4500
3     Neha   2400
4    Karan   2800

In [41]:
#print all ahmedabad rows use only loc fundtion
df.loc[df["City"] == "Ahmedabad"]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
3,104,Neha,Ahmedabad,Electronics,Mouse,3,2400,4.2
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
13,114,Pooja,Ahmedabad,Clothing,T-Shirt,5,3500,4.4

In [42]:
#only print ahmedabad customer name and sales use only loc
df.loc[df["City"] == "Ahmedabad",["Customer","Sales"]]

   Customer   Sales
0     Rahul   55000
3      Neha    2400
7    Anjali   10000
10      Dev  110000
13    Pooja    3500

In [43]:
#Select first rows using iloc
df.iloc[0]

Order_ID            101
Customer          Rahul
City          Ahmedabad
Category    Electronics
Product          Laptop
Quantity              1
Sales             55000
Rating              4.5
Name: 0, dtype: object

In [44]:
#Slect the first 5 rows using iloc
df.iloc[0:5,:]

   Order_ID Customer       City     Category  Product  Quantity  Sales  Rating
0       101    Rahul  Ahmedabad  Electronics   Laptop         1  55000     4.5
1       102    Priya     Mumbai     Clothing    Jeans         2   3600     4.0
2       103     Amit      Delhi      Grocery     Rice         5   4500     3.5
3       104     Neha  Ahmedabad  Electronics    Mouse         3   2400     4.2
4       105    Karan      Surat     Clothing  T-Shirt         4   2800     4.8

In [45]:
#select rows 2 to 6 and columns only customer name and product name 
df.iloc[2:7,[1,4]]

  Customer   Product
2     Amit      Rice
3     Neha     Mouse
4    Karan   T-Shirt
5     Riya  Keyboard
6    Mohit       Oil

In [46]:
#Select the last 3 rows and using iloc
df.iloc[-3:]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
12,113,Arjun,Surat,Grocery,Rice,6,5400,3.6
13,114,Pooja,Ahmedabad,Clothing,T-Shirt,5,3500,4.4
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [47]:
#Get the customer name at index 5 
df.at[5,"Customer"]

'Riya'

In [48]:
#Get the sales value at index 10 
df.at[10,"Sales"]

np.int64(110000)

In [49]:
#Get the value from row 5 and column 2
df.iat[5,2]

'Mumbai'

In [50]:
#Get the value from row 10 and column quentity 
df.iat[10,5]

np.int64(2)

#Filtering

In [51]:
#Find all order where sales 10000 up 
df[df["Sales"] >= 10000]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [54]:
#Find all orders where quentity 4 up
df[df["Quantity"] >=4]

    Order_ID Customer       City   Category  Product  Quantity  Sales  Rating
2        103     Amit      Delhi    Grocery     Rice         5   4500     3.5
4        105    Karan      Surat   Clothing  T-Shirt         4   2800     4.8
7        108   Anjali  Ahmedabad  Furniture    Chair         4  10000     4.6
12       113    Arjun      Surat    Grocery     Rice         6   5400     3.6
13       114    Pooja  Ahmedabad   Clothing  T-Shirt         5   3500     4.4

In [55]:
#Find all Electronics orders 
df[df["Category"] == "Electronics"]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
3,104,Neha,Ahmedabad,Electronics,Mouse,3,2400,4.2
5,106,Riya,Mumbai,Electronics,Keyboard,2,3000,4.1
8,109,Raj,Surat,Electronics,Headphones,2,4400,4.3
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [56]:
#Find all orders from ahmedabad 
df[df["City"] == "Ahmedabad"]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
3,104,Neha,Ahmedabad,Electronics,Mouse,3,2400,4.2
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
13,114,Pooja,Ahmedabad,Clothing,T-Shirt,5,3500,4.4

In [57]:
#Find orders where sales up 10000 and rating is 4.5 up 
df[(df["Sales"] >= 10000 ) & (df["Rating"] >= 4.5)]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [63]:
#Find orders where city is mumbai or surat 
df[(df["City"] == "Mumbai") | (df["City"] == "Surat")]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
1,102,Priya,Mumbai,Clothing,Jeans,2,3600,4.0
4,105,Karan,Surat,Clothing,T-Shirt,4,2800,4.8
5,106,Riya,Mumbai,Electronics,Keyboard,2,3000,4.1
8,109,Raj,Surat,Electronics,Headphones,2,4400,4.3
9,110,Simran,Mumbai,Clothing,Jeans,3,5400,3.9
12,113,Arjun,Surat,Grocery,Rice,6,5400,3.6
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

#Query method

In [64]:
#Find orders where sales up to 12000 
df.query("Sales >= 12000")

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [66]:
#Find Clothing orders 
df.query("Category == 'Clothing'")

    Order_ID Customer       City  Category  Product  Quantity  Sales  Rating
1        102    Priya     Mumbai  Clothing    Jeans         2   3600     4.0
4        105    Karan      Surat  Clothing  T-Shirt         4   2800     4.8
9        110   Simran     Mumbai  Clothing    Jeans         3   5400     3.9
13       114    Pooja  Ahmedabad  Clothing  T-Shirt         5   3500     4.4

In [67]:
#Find clothing high sales orders 
df.query("Category == 'Clothing'").max()

Order_ID         114
Customer      Simran
City           Surat
Category    Clothing
Product      T-Shirt
Quantity           5
Sales           5400
Rating           4.8
dtype: object

In [70]:
#Find orders where quentity is 4 up and rating is 4.0 to up 
df.query("Quantity >= 4 and Rating >= 4.5")

   Order_ID Customer       City   Category  Product  Quantity  Sales  Rating
4       105    Karan      Surat   Clothing  T-Shirt         4   2800     4.8
7       108   Anjali  Ahmedabad  Furniture    Chair         4  10000     4.6

In [72]:
#Find Mumbai orders with sales 5000 up 
df.query("City == 'Mumbai' and Sales >= 5000")

    Order_ID Customer    City     Category Product  Quantity  Sales  Rating
9        110   Simran  Mumbai     Clothing   Jeans         3   5400     3.9
14       115    Rohan  Mumbai  Electronics  Tablet         2  50000     4.5

In [74]:
#Select only customer city and sales columns 
df[["Customer","City","Sales"]]

   Customer       City   Sales
0     Rahul  Ahmedabad   55000
1     Priya     Mumbai    3600
2      Amit      Delhi    4500
3      Neha  Ahmedabad    2400
4     Karan      Surat    2800
5      Riya     Mumbai    3000
6     Mohit      Delhi    4500
7    Anjali  Ahmedabad   10000
8       Raj      Surat    4400
9    Simran     Mumbai    5400
10      Dev  Ahmedabad  110000
11    Meena      Delhi    6500
12    Arjun      Surat    5400
13    Pooja  Ahmedabad    3500
14    Rohan     Mumbai   50000

In [75]:
#Select first 7 rows and only product and sales columns 
df.loc[0:7,["Product","Sales"]]

    Product  Sales
0    Laptop  55000
1     Jeans   3600
2      Rice   4500
3     Mouse   2400
4   T-Shirt   2800
5  Keyboard   3000
6       Oil   4500
7     Chair  10000

In [77]:
#Select customer and rating for all orders from mumbai 
df.loc[df["City"] == "Mumbai",["City","Customer","Product","Rating"]]

      City Customer   Product  Rating
1   Mumbai    Priya     Jeans     4.0
5   Mumbai     Riya  Keyboard     4.1
9   Mumbai   Simran     Jeans     3.9
14  Mumbai    Rohan    Tablet     4.5

In [79]:
#Find all orders where sales is 5000 up and quantity 2 up
df[(df["Sales"] >= 5000) & (df["Quantity"] >= 2)]

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
9,110,Simran,Mumbai,Clothing,Jeans,3,5400,3.9
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
12,113,Arjun,Surat,Grocery,Rice,6,5400,3.6
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [82]:
#Find all electronics orders where rating is 4.5 to up
df.query("Category == 'Electronics' and Rating >= 4.5")

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [84]:
#Find orders from Ahmedabad and surat 
df.query("City == 'Ahmedabad' or City == 'Surat'")

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
3,104,Neha,Ahmedabad,Electronics,Mouse,3,2400,4.2
4,105,Karan,Surat,Clothing,T-Shirt,4,2800,4.8
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
8,109,Raj,Surat,Electronics,Headphones,2,4400,4.3
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
12,113,Arjun,Surat,Grocery,Rice,6,5400,3.6
13,114,Pooja,Ahmedabad,Clothing,T-Shirt,5,3500,4.4

In [89]:
#Find orders where sales 15000 up and rating is 4 up 
df.query("Sales >= 15000 and Rating >= 4.0")

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7
14,115,Rohan,Mumbai,Electronics,Tablet,2,50000,4.5

In [90]:
#Find clothing orders with quantity is 3 to up 
df.query("Category == 'Clothing' and Quantity >= 3")

    Order_ID Customer       City  Category  Product  Quantity  Sales  Rating
4        105    Karan      Surat  Clothing  T-Shirt         4   2800     4.8
9        110   Simran     Mumbai  Clothing    Jeans         3   5400     3.9
13       114    Pooja  Ahmedabad  Clothing  T-Shirt         5   3500     4.4

In [92]:
#Find jeans sales and rating 
df.query("Product == 'Jeans'")

   Order_ID Customer    City  Category Product  Quantity  Sales  Rating
1       102    Priya  Mumbai  Clothing   Jeans         2   3600     4.0
9       110   Simran  Mumbai  Clothing   Jeans         3   5400     3.9

In [94]:
#Select 3 to 8 rows and columns 1 to 5 
df.iloc[3:9,1:6]

  Customer       City     Category     Product  Quantity
3     Neha  Ahmedabad  Electronics       Mouse         3
4    Karan      Surat     Clothing     T-Shirt         4
5     Riya     Mumbai  Electronics    Keyboard         2
6    Mohit      Delhi      Grocery         Oil         3
7   Anjali  Ahmedabad    Furniture       Chair         4
8      Raj      Surat  Electronics  Headphones         2

In [102]:
df.query("City == 'Ahmedabad' and Sales >= 10000 and Rating >= 4.5")

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Rating
0,101,Rahul,Ahmedabad,Electronics,Laptop,1,55000,4.5
7,108,Anjali,Ahmedabad,Furniture,Chair,4,10000,4.6
10,111,Dev,Ahmedabad,Electronics,Laptop,2,110000,4.7