In [3]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\1745501008647-data_cleaning_sample.csv")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
df.isnull()   #True is NaN value

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [7]:
#Count NaN value 
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [8]:
#Drop NaN rows
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [9]:
#drop NaN column
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [10]:
#Fill misiing value 
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [11]:
#Age NaN value replace age mean value 
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [12]:
#Fill ALL VALUE USE FFILL() Forward fill
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [13]:
#fill NaN Use bfill (Backward fill)
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [15]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [14]:
#Detecting to duplicate rows 
df.duplicated()  #True is duplicate rows

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [16]:
#Remove duplicate rows 
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

#Use string method

In [25]:
df["Name"] = df["Name"].str.title()

In [26]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [28]:
#Convert name columns lower case 
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [31]:
#Chack David is in the Name columns 
df["Name"].str.contains("david",case=False)

0    False
1    False
2    False
3    False
4     True
5      NaN
6    False
7    False
8    False
Name: Name, dtype: object

In [32]:
#Email convert upper case 
df["Email"].str.upper()

0    ALICE@EXAMPLE.COM
1      CHARLIE@EXAMPLE
2      BOB@EXAMPLE.COM
3      CHARLIE@EXAMPLE
4    DAVID@EXAMPLE.COM
5       EVE@DOMAIN.COM
6    ALICE@EXAMPLE.COM
7    ALICE@EXAMPLE.COM
8      CHARLIE@EXAMPLE
Name: Email, dtype: object

In [42]:
#Alice name convert to Rocky
df["Name"].str.replace("Alice","Rocky")

0      Rocky
1    Charlie
2        Bob
3    Charlie
4      David
5        NaN
6      Rocky
7      Rocky
8    Charlie
Name: Name, dtype: object

#Type conversion

In [45]:
#Age is float convert integer 
df["Age"].ffill().astype(int)

0    25
1    25
2    30
3    30
4    22
5    28
6    25
7    25
8    25
Name: Age, dtype: int64

In [48]:
df["Join Date"].ffill()

0    01-05-2021
1    20-07-2021
2    15-06-2020
3    20-07-2021
4    12-11-2019
5    12-11-2019
6    01-05-2021
7    01-05-2021
8    20-07-2021
Name: Join Date, dtype: object

In [51]:
df["Gender"].map({"M":"Male","F":"Female"})

0    Female
1      Male
2      Male
3      Male
4      Male
5    Female
6    Female
7    Female
8      Male
Name: Gender, dtype: object

In [55]:
#Delhi convert new delhi and Mumbai convert New Mumbai
df["City"].replace({"Delhi":"New Delhi","Mumbai":"New Mumbai"})

0       New York
1      New Delhi
2    Los Angeles
3      New Delhi
4     New Mumbai
5      New Delhi
6       New York
7       New York
8      New Delhi
Name: City, dtype: object

#Same data cleaning propar

In [57]:
df1 = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\1745501008647-data_cleaning_sample.csv")
df1

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [80]:
#Remove duplicate rows 
df2 = df1.drop_duplicates()

In [86]:
#NaN name fill Unkonown
df2["Name"] = df2["Name"].fillna("Unkonown")

In [85]:
#Age fill and convert int 
df2["Age"] = df2["Age"].ffill().astype(int)

In [84]:
#Gender convert full name 
df2["Gender"] = df2["Gender"].replace({"F":"Female","M":"Male"})

In [83]:
#Email convert tital form
df2["Email"] = df2["Email"].str.title()

In [82]:
#Fill NaN Date 
df2["Join Date"] = df2["Join Date"].ffill()

In [87]:
#Clean data 
df2

       Name  Age         City  Gender              Email   Join Date
0     Alice   25     New York  Female  Alice@Example.Com  01-05-2021
1   Charlie   25        Delhi    Male    Charlie@Example  20-07-2021
2       Bob   30  Los Angeles    Male    Bob@Example.Com  15-06-2020
3   Charlie   30        Delhi    Male    Charlie@Example  20-07-2021
4     David   22       Mumbai    Male  David@Example.Com  12-11-2019
5  Unkonown   28        Delhi  Female     Eve@Domain.Com  12-11-2019