In [1]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\1745501008647-data_cleaning_sample.csv")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [26]:
df.isnull()   #True is NaN value

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [27]:
#Count NaN value 
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [28]:
#Drop NaN rows
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [29]:
#drop NaN column
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [30]:
#Fill misiing value 
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [31]:
#Age NaN value replace age mean value 
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [32]:
#Fill ALL VALUE USE FFILL() Forward fill
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [33]:
#fill NaN Use bfill (Backward fill)
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [34]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [35]:
#Detecting to duplicate rows 
df.duplicated()  #True is duplicate rows

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [36]:
#Remove duplicate rows 
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

#Use string method

In [37]:
df["Name"] = df["Name"].str.title()

In [38]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [39]:
#Convert name columns lower case 
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [40]:
#Chack David is in the Name columns 
df["Name"].str.contains("david",case=False)

0    False
1    False
2    False
3    False
4     True
5      NaN
6    False
7    False
8    False
Name: Name, dtype: object

In [41]:
#Email convert upper case 
df["Email"].str.upper()

0    ALICE@EXAMPLE.COM
1      CHARLIE@EXAMPLE
2      BOB@EXAMPLE.COM
3      CHARLIE@EXAMPLE
4    DAVID@EXAMPLE.COM
5       EVE@DOMAIN.COM
6    ALICE@EXAMPLE.COM
7    ALICE@EXAMPLE.COM
8      CHARLIE@EXAMPLE
Name: Email, dtype: object

In [42]:
#Alice name convert to Rocky
df["Name"].str.replace("Alice","Rocky")

0      Rocky
1    Charlie
2        Bob
3    Charlie
4      David
5        NaN
6      Rocky
7      Rocky
8    Charlie
Name: Name, dtype: object

#Type conversion

In [43]:
#Age is float convert integer 
df["Age"].ffill().astype(int)

0    25
1    25
2    30
3    30
4    22
5    28
6    25
7    25
8    25
Name: Age, dtype: int64

In [44]:
df["Join Date"].ffill()

0    01-05-2021
1    20-07-2021
2    15-06-2020
3    20-07-2021
4    12-11-2019
5    12-11-2019
6    01-05-2021
7    01-05-2021
8    20-07-2021
Name: Join Date, dtype: object

In [45]:
df["Gender"].map({"M":"Male","F":"Female"})

0    Female
1      Male
2      Male
3      Male
4      Male
5    Female
6    Female
7    Female
8      Male
Name: Gender, dtype: object

In [46]:
#Delhi convert new delhi and Mumbai convert New Mumbai
df["City"].replace({"Delhi":"New Delhi","Mumbai":"New Mumbai"})

0       New York
1      New Delhi
2    Los Angeles
3      New Delhi
4     New Mumbai
5      New Delhi
6       New York
7       New York
8      New Delhi
Name: City, dtype: object

#Same data cleaning propar

In [47]:
df1 = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\1745501008647-data_cleaning_sample.csv")
df1

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [48]:
#Remove duplicate rows 
df2 = df1.drop_duplicates().copy()

In [49]:
#NaN name fill Unkonown
df2["Name"] = df2["Name"].fillna("Unkonown")

In [50]:
#Age fill and convert int 
df2["Age"] = df2["Age"].ffill().astype(int)

In [51]:
#Gender convert full name 
df2["Gender"] = df2["Gender"].replace({"F":"Female","M":"Male"})

In [52]:
#Email convert tital form
df2["Email"] = df2["Email"].str.title()

In [53]:
#Fill NaN Date 
df2["Join Date"] = df2["Join Date"].ffill()

In [54]:
#Clean data 
df2

       Name  Age         City  Gender              Email   Join Date
0     Alice   25     New York  Female  Alice@Example.Com  01-05-2021
1   Charlie   25        Delhi    Male    Charlie@Example  20-07-2021
2       Bob   30  Los Angeles    Male    Bob@Example.Com  15-06-2020
4     David   22       Mumbai    Male  David@Example.Com  12-11-2019
5  Unkonown   28        Delhi  Female     Eve@Domain.Com  12-11-2019

#New data set practice

In [55]:
data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\year_employee_pandas_practice.csv")
data

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
0          1001    Aarav         IT  55000.0         2.0  Ahmedabad       2021
1          1002     Diya         HR  48000.0         1.0     Mumbai       2022
2          1003   Rohan     Finance  62000.0         4.0       Pune       2020
3          1004    Anaya         IT      NaN         5.0  Ahmedabad       2019
4          1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023
5          1006   Ishita         HR  52000.0         3.0  Ahmedabad       2021
6          1007   Aditya         IT  68000.0         NaN     mumbai       2020
7          1008     Myra  Marketing  58000.0         2.0       Pune       2022
8          1009    Arjun    Finance  60000.0         3.0      Delhi       2018
9          1010    Kiara        IT   75000.0         6.0  Ahmedabad       2019
10         1011  Reyansh      Sales  50000.0         2.0     Mumbai       2023
11         1012     Avni         HR  51000.0         1.0      Delhi       2022
12         1013    Kabir         IT  72000.0         5.0  Ahmedabad       2020
13         1014     Sara    Finance  65000.0         4.0       Pune       2018
14         1015   Atharv  Marketing      NaN         2.0  Bengaluru       2021
15         1016     Riya         IT  78000.0         7.0      Delhi       2017
16         1017      Dev      Sales  59000.0         3.0     Mumbai       2022
17         1018     Tara         HR  47000.0         1.0  Ahmedabad       2023
18         1019     Yash    Finance  69000.0         5.0       Pune       2019
19         1020    Nisha         IT  56000.0         3.0  Bengaluru       2020
20         1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023

In [56]:
#Chack first 5 rows 
data.head()

   Employee_ID     Name Department   Salary  Experience       City  Join_Year
0         1001    Aarav         IT  55000.0         2.0  Ahmedabad       2021
1         1002     Diya         HR  48000.0         1.0     Mumbai       2022
2         1003   Rohan     Finance  62000.0         4.0       Pune       2020
3         1004    Anaya         IT      NaN         5.0  Ahmedabad       2019
4         1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023

In [57]:
#Find the number of rows and columns 
data.shape

(21, 7)

In [58]:
#Chack display columns name 
data.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience', 'City',
       'Join_Year'],
      dtype='object')

In [59]:
#Chack the data type of all columns 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  21 non-null     int64
 1   Name         21 non-null     object
 2   Department   21 non-null     object
 3   Salary       19 non-null     float64
 4   Experience   20 non-null     float64
 5   City         21 non-null     object
 6   Join_Year    21 non-null     int64
dtypes: float64(2), int64(2), object(3)
memory usage: 1.3+ KB

#Data selection

In [60]:
#Select only the name column
data["Name"]

0       Aarav
1        Diya
2      Rohan
3       Anaya
4      Vivaan
5      Ishita
6      Aditya
7        Myra
8       Arjun
9       Kiara
10    Reyansh
11       Avni
12      Kabir
13       Sara
14     Atharv
15       Riya
16        Dev
17       Tara
18       Yash
19      Nisha
20     Vivaan
Name: Name, dtype: object

In [61]:
#Select Name and Salary columns 
data[["Name","Salary"]]

       Name   Salary
0     Aarav  55000.0
1      Diya  48000.0
2    Rohan   62000.0
3     Anaya      NaN
4    Vivaan  45000.0
5    Ishita  52000.0
6    Aditya  68000.0
7      Myra  58000.0
8     Arjun  60000.0
9     Kiara  75000.0
10  Reyansh  50000.0
11     Avni  51000.0
12    Kabir  72000.0
13     Sara  65000.0
14   Atharv      NaN
15     Riya  78000.0
16      Dev  59000.0
17     Tara  47000.0
18     Yash  69000.0
19    Nisha  56000.0
20   Vivaan  45000.0

In [62]:
#Select Department city and join_year columns 
data[["Name","Department","City","Join_Year"]]

       Name Department       City  Join_Year
0     Aarav         IT  Ahmedabad       2021
1      Diya         HR     Mumbai       2022
2    Rohan     Finance       Pune       2020
3     Anaya         IT  Ahmedabad       2019
4    Vivaan      Sales     Mumbai       2023
5    Ishita         HR  Ahmedabad       2021
6    Aditya         IT     mumbai       2020
7      Myra  Marketing       Pune       2022
8     Arjun    Finance      Delhi       2018
9     Kiara        IT   Ahmedabad       2019
10  Reyansh      Sales     Mumbai       2023
11     Avni         HR      Delhi       2022
12    Kabir         IT  Ahmedabad       2020
13     Sara    Finance       Pune       2018
14   Atharv  Marketing  Bengaluru       2021
15     Riya         IT      Delhi       2017
16      Dev      Sales     Mumbai       2022
17     Tara         HR  Ahmedabad       2023
18     Yash    Finance       Pune       2019
19    Nisha         IT  Bengaluru       2020
20   Vivaan      Sales     Mumbai       2023

In [63]:
#Select the first 5 rows 
data.loc[0:4]

   Employee_ID     Name Department   Salary  Experience       City  Join_Year
0         1001    Aarav         IT  55000.0         2.0  Ahmedabad       2021
1         1002     Diya         HR  48000.0         1.0     Mumbai       2022
2         1003   Rohan     Finance  62000.0         4.0       Pune       2020
3         1004    Anaya         IT      NaN         5.0  Ahmedabad       2019
4         1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023

In [64]:
#Select 3 rows and Name department 
data.loc[0:2,["Name","Department"]]

      Name Department
0    Aarav         IT
1     Diya         HR
2   Rohan     Finance

In [65]:
#Select rows from position 3 to position 8
data.iloc[0:4,3:8]

    Salary  Experience       City  Join_Year
0  55000.0         2.0  Ahmedabad       2021
1  48000.0         1.0     Mumbai       2022
2  62000.0         4.0       Pune       2020
3      NaN         5.0  Ahmedabad       2019

In [66]:
#Select the row of employe_id 1005
data.loc[4]

Employee_ID       1005
Name            Vivaan
Department       Sales
Salary         45000.0
Experience         1.0
City            Mumbai
Join_Year         2023
Name: 4, dtype: object

In [67]:
#Select only Name and salary for employe_id 1010
data.loc[9,["Name","Salary"]]

Name        Kiara
Salary    75000.0
Name: 9, dtype: object

In [68]:
#Find the salary of Employee_id 1003
data.at[2,"Salary"]

np.float64(62000.0)

In [69]:
#Find the value from the first row and third column
data.iat[0,2]

'IT'

#Filtering

In [70]:
#Filter employees whose salary is 60000 up
data[data["Salary"] >= 60000]

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
2          1003   Rohan     Finance  62000.0         4.0       Pune       2020
6          1007   Aditya         IT  68000.0         NaN     mumbai       2020
8          1009    Arjun    Finance  60000.0         3.0      Delhi       2018
9          1010    Kiara        IT   75000.0         6.0  Ahmedabad       2019
12         1013    Kabir         IT  72000.0         5.0  Ahmedabad       2020
13         1014     Sara    Finance  65000.0         4.0       Pune       2018
15         1016     Riya         IT  78000.0         7.0      Delhi       2017
18         1019     Yash    Finance  69000.0         5.0       Pune       2019

In [71]:
#Filter employe who work in the IT department 
data[data["Department"] == "IT"]

    Employee_ID    Name Department   Salary  Experience       City  Join_Year
0          1001   Aarav         IT  55000.0         2.0  Ahmedabad       2021
3          1004   Anaya         IT      NaN         5.0  Ahmedabad       2019
6          1007  Aditya         IT  68000.0         NaN     mumbai       2020
12         1013   Kabir         IT  72000.0         5.0  Ahmedabad       2020
15         1016    Riya         IT  78000.0         7.0      Delhi       2017
19         1020   Nisha         IT  56000.0         3.0  Bengaluru       2020

In [72]:
#Filter employe whose experience is 4 year 
data[data["Experience"] >= 4]

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
2          1003   Rohan     Finance  62000.0         4.0       Pune       2020
3          1004    Anaya         IT      NaN         5.0  Ahmedabad       2019
9          1010    Kiara        IT   75000.0         6.0  Ahmedabad       2019
12         1013    Kabir         IT  72000.0         5.0  Ahmedabad       2020
13         1014     Sara    Finance  65000.0         4.0       Pune       2018
15         1016     Riya         IT  78000.0         7.0      Delhi       2017
18         1019     Yash    Finance  69000.0         5.0       Pune       2019

In [73]:
#Filter employes who joined in the year 2020
data[data["Join_Year"] == 2020]

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
2          1003   Rohan     Finance  62000.0         4.0       Pune       2020
6          1007   Aditya         IT  68000.0         NaN     mumbai       2020
12         1013    Kabir         IT  72000.0         5.0  Ahmedabad       2020
19         1020    Nisha         IT  56000.0         3.0  Bengaluru       2020

In [74]:
#Filter employes whose join_year is after 2020
data[data['Join_Year'] > 2020]

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
0          1001    Aarav         IT  55000.0         2.0  Ahmedabad       2021
1          1002     Diya         HR  48000.0         1.0     Mumbai       2022
4          1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023
5          1006   Ishita         HR  52000.0         3.0  Ahmedabad       2021
7          1008     Myra  Marketing  58000.0         2.0       Pune       2022
10         1011  Reyansh      Sales  50000.0         2.0     Mumbai       2023
11         1012     Avni         HR  51000.0         1.0      Delhi       2022
14         1015   Atharv  Marketing      NaN         2.0  Bengaluru       2021
16         1017      Dev      Sales  59000.0         3.0     Mumbai       2022
17         1018     Tara         HR  47000.0         1.0  Ahmedabad       2023
20         1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023

In [75]:
#Filter employes who are from IT and have salary is 65000 up
data[(data["Department"] == "IT") & (data["Salary"] >= 65000)]

    Employee_ID    Name Department   Salary  Experience       City  Join_Year
6          1007  Aditya         IT  68000.0         NaN     mumbai       2020
12         1013   Kabir         IT  72000.0         5.0  Ahmedabad       2020
15         1016    Riya         IT  78000.0         7.0      Delhi       2017

In [76]:
#Who are from HR Or sales
data[(data['Department'] == "HR") | (data['Department'] == "Sales")]

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
1          1002     Diya         HR  48000.0         1.0     Mumbai       2022
4          1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023
5          1006   Ishita         HR  52000.0         3.0  Ahmedabad       2021
10         1011  Reyansh      Sales  50000.0         2.0     Mumbai       2023
11         1012     Avni         HR  51000.0         1.0      Delhi       2022
16         1017      Dev      Sales  59000.0         3.0     Mumbai       2022
17         1018     Tara         HR  47000.0         1.0  Ahmedabad       2023
20         1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023

#Use Query method

In [77]:
#Find employes whose Salary is 60000 up
data.query("Salary >= 60000")

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
2          1003   Rohan     Finance  62000.0         4.0       Pune       2020
6          1007   Aditya         IT  68000.0         NaN     mumbai       2020
8          1009    Arjun    Finance  60000.0         3.0      Delhi       2018
9          1010    Kiara        IT   75000.0         6.0  Ahmedabad       2019
12         1013    Kabir         IT  72000.0         5.0  Ahmedabad       2020
13         1014     Sara    Finance  65000.0         4.0       Pune       2018
15         1016     Riya         IT  78000.0         7.0      Delhi       2017
18         1019     Yash    Finance  69000.0         5.0       Pune       2019

In [78]:
#Find who employess work Ahmedabad
data.query("City == 'Ahmedabad'")

    Employee_ID    Name Department   Salary  Experience       City  Join_Year
0          1001   Aarav         IT  55000.0         2.0  Ahmedabad       2021
3          1004   Anaya         IT      NaN         5.0  Ahmedabad       2019
5          1006  Ishita         HR  52000.0         3.0  Ahmedabad       2021
9          1010   Kiara        IT   75000.0         6.0  Ahmedabad       2019
12         1013   Kabir         IT  72000.0         5.0  Ahmedabad       2020
17         1018    Tara         HR  47000.0         1.0  Ahmedabad       2023

#Data Cleaning

In [79]:
#Find the missing value in every columns 
data.isnull()     #True is missing value

    Employee_ID   Name  Department  Salary  Experience   City  Join_Year
0         False  False       False   False       False  False      False
1         False  False       False   False       False  False      False
2         False  False       False   False       False  False      False
3         False  False       False    True       False  False      False
4         False  False       False   False       False  False      False
5         False  False       False   False       False  False      False
6         False  False       False   False        True  False      False
7         False  False       False   False       False  False      False
8         False  False       False   False       False  False      False
9         False  False       False   False       False  False      False
10        False  False       False   False       False  False      False
11        False  False       False   False       False  False      False
12        False  False       False   False       False  False      False
13        False  False       False   False       False  False      False
14        False  False       False    True       False  False      False
15        False  False       False   False       False  False      False
16        False  False       False   False       False  False      False
17        False  False       False   False       False  False      False
18        False  False       False   False       False  False      False
19        False  False       False   False       False  False      False
20        False  False       False   False       False  False      False

In [80]:
#Count Misiing value 
data.isnull().sum()

Employee_ID    0
Name           0
Department     0
Salary         2
Experience     1
City           0
Join_Year      0
dtype: int64

In [81]:
#Chack duplicate rows 
data.duplicated()   #True is Duplicate rows

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [82]:
#Remove Duplicate rows 
data.drop_duplicates()

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
0          1001    Aarav         IT  55000.0         2.0  Ahmedabad       2021
1          1002     Diya         HR  48000.0         1.0     Mumbai       2022
2          1003   Rohan     Finance  62000.0         4.0       Pune       2020
3          1004    Anaya         IT      NaN         5.0  Ahmedabad       2019
4          1005   Vivaan      Sales  45000.0         1.0     Mumbai       2023
5          1006   Ishita         HR  52000.0         3.0  Ahmedabad       2021
6          1007   Aditya         IT  68000.0         NaN     mumbai       2020
7          1008     Myra  Marketing  58000.0         2.0       Pune       2022
8          1009    Arjun    Finance  60000.0         3.0      Delhi       2018
9          1010    Kiara        IT   75000.0         6.0  Ahmedabad       2019
10         1011  Reyansh      Sales  50000.0         2.0     Mumbai       2023
11         1012     Avni         HR  51000.0         1.0      Delhi       2022
12         1013    Kabir         IT  72000.0         5.0  Ahmedabad       2020
13         1014     Sara    Finance  65000.0         4.0       Pune       2018
14         1015   Atharv  Marketing      NaN         2.0  Bengaluru       2021
15         1016     Riya         IT  78000.0         7.0      Delhi       2017
16         1017      Dev      Sales  59000.0         3.0     Mumbai       2022
17         1018     Tara         HR  47000.0         1.0  Ahmedabad       2023
18         1019     Yash    Finance  69000.0         5.0       Pune       2019
19         1020    Nisha         IT  56000.0         3.0  Bengaluru       2020

In [83]:
#Remove extra space from the name column
data["Name"] = data["Name"].str.strip()
print(data["Name"])

0       Aarav
1        Diya
2       Rohan
3       Anaya
4      Vivaan
5      Ishita
6      Aditya
7        Myra
8       Arjun
9       Kiara
10    Reyansh
11       Avni
12      Kabir
13       Sara
14     Atharv
15       Riya
16        Dev
17       Tara
18       Yash
19      Nisha
20     Vivaan
Name: Name, dtype: object

#Missing values & Preprocessing

In [84]:
#Fill missing salary values using median salary 
data["Salary"] = data["Salary"].fillna(data["Salary"].median())
print(data["Salary"])

0     55000.0
1     48000.0
2     62000.0
3     58000.0
4     45000.0
5     52000.0
6     68000.0
7     58000.0
8     60000.0
9     75000.0
10    50000.0
11    51000.0
12    72000.0
13    65000.0
14    58000.0
15    78000.0
16    59000.0
17    47000.0
18    69000.0
19    56000.0
20    45000.0
Name: Salary, dtype: float64

In [85]:
#Fill missing experience values replace mean 
data["Experience"] = data["Experience"].fillna(data["Experience"].mean())
data

    Employee_ID     Name Department   Salary  Experience       City  Join_Year
0          1001    Aarav         IT  55000.0        2.00  Ahmedabad       2021
1          1002     Diya         HR  48000.0        1.00     Mumbai       2022
2          1003    Rohan    Finance  62000.0        4.00       Pune       2020
3          1004    Anaya         IT  58000.0        5.00  Ahmedabad       2019
4          1005   Vivaan      Sales  45000.0        1.00     Mumbai       2023
5          1006   Ishita         HR  52000.0        3.00  Ahmedabad       2021
6          1007   Aditya         IT  68000.0        3.05     mumbai       2020
7          1008     Myra  Marketing  58000.0        2.00       Pune       2022
8          1009    Arjun    Finance  60000.0        3.00      Delhi       2018
9          1010    Kiara        IT   75000.0        6.00  Ahmedabad       2019
10         1011  Reyansh      Sales  50000.0        2.00     Mumbai       2023
11         1012     Avni         HR  51000.0        1.00      Delhi       2022
12         1013    Kabir         IT  72000.0        5.00  Ahmedabad       2020
13         1014     Sara    Finance  65000.0        4.00       Pune       2018
14         1015   Atharv  Marketing  58000.0        2.00  Bengaluru       2021
15         1016     Riya         IT  78000.0        7.00      Delhi       2017
16         1017      Dev      Sales  59000.0        3.00     Mumbai       2022
17         1018     Tara         HR  47000.0        1.00  Ahmedabad       2023
18         1019     Yash    Finance  69000.0        5.00       Pune       2019
19         1020    Nisha         IT  56000.0        3.00  Bengaluru       2020
20         1005   Vivaan      Sales  45000.0        1.00     Mumbai       2023

In [86]:
#Salary and Experience columns is Float values convert integer value 
data[["Salary","Experience"]] = data[["Salary","Experience"]].astype(int)
data

    Employee_ID     Name Department  Salary  Experience       City  Join_Year
0          1001    Aarav         IT   55000           2  Ahmedabad       2021
1          1002     Diya         HR   48000           1     Mumbai       2022
2          1003    Rohan    Finance   62000           4       Pune       2020
3          1004    Anaya         IT   58000           5  Ahmedabad       2019
4          1005   Vivaan      Sales   45000           1     Mumbai       2023
5          1006   Ishita         HR   52000           3  Ahmedabad       2021
6          1007   Aditya         IT   68000           3     mumbai       2020
7          1008     Myra  Marketing   58000           2       Pune       2022
8          1009    Arjun    Finance   60000           3      Delhi       2018
9          1010    Kiara        IT    75000           6  Ahmedabad       2019
10         1011  Reyansh      Sales   50000           2     Mumbai       2023
11         1012     Avni         HR   51000           1      Delhi       2022
12         1013    Kabir         IT   72000           5  Ahmedabad       2020
13         1014     Sara    Finance   65000           4       Pune       2018
14         1015   Atharv  Marketing   58000           2  Bengaluru       2021
15         1016     Riya         IT   78000           7      Delhi       2017
16         1017      Dev      Sales   59000           3     Mumbai       2022
17         1018     Tara         HR   47000           1  Ahmedabad       2023
18         1019     Yash    Finance   69000           5       Pune       2019
19         1020    Nisha         IT   56000           3  Bengaluru       2020
20         1005   Vivaan      Sales   45000           1     Mumbai       2023

In [87]:
data = data.drop_duplicates()
data

    Employee_ID     Name Department  Salary  Experience       City  Join_Year
0          1001    Aarav         IT   55000           2  Ahmedabad       2021
1          1002     Diya         HR   48000           1     Mumbai       2022
2          1003    Rohan    Finance   62000           4       Pune       2020
3          1004    Anaya         IT   58000           5  Ahmedabad       2019
4          1005   Vivaan      Sales   45000           1     Mumbai       2023
5          1006   Ishita         HR   52000           3  Ahmedabad       2021
6          1007   Aditya         IT   68000           3     mumbai       2020
7          1008     Myra  Marketing   58000           2       Pune       2022
8          1009    Arjun    Finance   60000           3      Delhi       2018
9          1010    Kiara        IT    75000           6  Ahmedabad       2019
10         1011  Reyansh      Sales   50000           2     Mumbai       2023
11         1012     Avni         HR   51000           1      Delhi       2022
12         1013    Kabir         IT   72000           5  Ahmedabad       2020
13         1014     Sara    Finance   65000           4       Pune       2018
14         1015   Atharv  Marketing   58000           2  Bengaluru       2021
15         1016     Riya         IT   78000           7      Delhi       2017
16         1017      Dev      Sales   59000           3     Mumbai       2022
17         1018     Tara         HR   47000           1  Ahmedabad       2023
18         1019     Yash    Finance   69000           5       Pune       2019
19         1020    Nisha         IT   56000           3  Bengaluru       2020

#Revision

In [103]:
data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\pandas_cleaning_practice_10_rows.csv")
data

,Employee_ID,Name,City,Department,Salary,Joining_Date,Performance,Status
0,101,rahul,ahmedabad,sales,25000,2024-01-15,4.2,active
1,102,PRIYA,MUMBAI,SALES,30000,15/02/2024,3.8,ACTIVE
2,103,Amit,Delhi,it,NaN,2024-03-10,NaN,inactive
3,104,NaN,ahmedabad,HR,28000,NaN,4.5,active
4,105,neha,NaN,sales,35000,2024-05-20,4.0,NaN
5,105,neha,ahmedabad,sales,35000,2024-05-20,4.0,active
6,107,Karan,surat,NaN,40000,2024-07-01,3.5,inactive
7,108,riya,Mumbai,IT,32000,01-08-2024,NaN,Active
8,109,MOHIT,DELHI,hr,abc,2024/09/15,4.8,INACTIVE
9,110,Anjali,surat,Sales,45000,2024-10-05,4.1,active

In [104]:
#Chack missing value 
data.isnull()      #True is missing value

,Employee_ID,Name,City,Department,Salary,Joining_Date,Performance,Status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,True,False
3,False,True,False,False,False,True,False,False
4,False,False,True,False,False,False,False,True
5,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False

In [105]:
#Find total missing value 
data.isnull().sum()

Employee_ID     0
Name            1
City            1
Department      1
Salary          1
Joining_Date    1
Performance     2
Status          1
dtype: int64

In [106]:
#Drop rows containing missing values
data.dropna()

,Employee_ID,Name,City,Department,Salary,Joining_Date,Performance,Status
0,101,rahul,ahmedabad,sales,25000,2024-01-15,4.2,active
1,102,PRIYA,MUMBAI,SALES,30000,15/02/2024,3.8,ACTIVE
5,105,neha,ahmedabad,sales,35000,2024-05-20,4.0,active
8,109,MOHIT,DELHI,hr,abc,2024/09/15,4.8,INACTIVE
9,110,Anjali,surat,Sales,45000,2024-10-05,4.1,active

In [107]:
#Fill missing performance value with the mean 
data["Performance"].fillna(data["Performance"].mean())

0    4.2000
1    3.8000
2    4.1125
3    4.5000
4    4.0000
5    4.0000
6    3.5000
7    4.1125
8    4.8000
9    4.1000
Name: Performance, dtype: float64

In [108]:
#Fill missing status values using forward
data["Status"].ffill()

0      active
1      ACTIVE
2    inactive
3      active
4      active
5      active
6    inactive
7      Active
8    INACTIVE
9      active
Name: Status, dtype: object

In [109]:
#Fill missing name values using backward 
data["Name"].bfill()

0     rahul
1      PRIYA
2       Amit
3       neha
4       neha
5       neha
6     Karan
7       riya
8      MOHIT
9     Anjali
Name: Name, dtype: object

In [110]:
#Chack duplicate rows
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [111]:
#Use string methods 
#Remove extra spaces from the name columns 
data["Name"].str.strip()

0     rahul
1     PRIYA
2      Amit
3       NaN
4      neha
5      neha
6     Karan
7      riya
8     MOHIT
9    Anjali
Name: Name, dtype: object

In [112]:
#Convert all name value into title case 
data["Name"].str.title()

0     Rahul
1      Priya
2       Amit
3        NaN
4       Neha
5       Neha
6     Karan
7       Riya
8      Mohit
9     Anjali
Name: Name, dtype: object

In [113]:
#Convert city name value into lower case
data["City"].str.lower()

0    ahmedabad
1      mumbai
2        delhi
3    ahmedabad
4          NaN
5    ahmedabad
6        surat
7       mumbai
8        delhi
9        surat
Name: City, dtype: object

In [114]:
#Convert department values into uppercase
data["Department"].str.upper()

0    SALES
1    SALES
2       IT
3       HR
4    SALES
5    SALES
6      NaN
7       IT
8       HR
9    SALES
Name: Department, dtype: object

In [116]:
#Convert Status columns into tital case
data["Status"].str.title()

0      Active
1      Active
2    Inactive
3      Active
4         NaN
5      Active
6    Inactive
7      Active
8    Inactive
9      Active
Name: Status, dtype: object

In [118]:
#Chack mumbai is in the city column
data["City"].str.contains("mumbai",case=False)    #True is mumbai name

0    False
1     True
2    False
3    False
4      NaN
5    False
6    False
7     True
8    False
9    False
Name: City, dtype: object

In [129]:
#Convert Salary into a numeric 
data["Salary"] = pd.to_numeric(data["Salary"],errors='coerce')
print(data["Salary"])

0    25000.0
1    30000.0
2        NaN
3    28000.0
4    35000.0
5    35000.0
6    40000.0
7    32000.0
8        NaN
9    45000.0
Name: Salary, dtype: float64

In [131]:
#Find which salary value is non-numeric
data["Salary"] = pd.to_numeric(data["Salary"],errors='coerce').isna()
print(data["Salary"])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Salary, dtype: bool

#clean New_Data

In [2]:
new_data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\pandas_cleaning_practice_10_rows.csv")
new_data

,Employee_ID,Name,City,Department,Salary,Joining_Date,Performance,Status
0,101,rahul,ahmedabad,sales,25000,2024-01-15,4.2,active
1,102,PRIYA,MUMBAI,SALES,30000,15/02/2024,3.8,ACTIVE
2,103,Amit,Delhi,it,NaN,2024-03-10,NaN,inactive
3,104,NaN,ahmedabad,HR,28000,NaN,4.5,active
4,105,neha,NaN,sales,35000,2024-05-20,4.0,NaN
5,105,neha,ahmedabad,sales,35000,2024-05-20,4.0,active
6,107,Karan,surat,NaN,40000,2024-07-01,3.5,inactive
7,108,riya,Mumbai,IT,32000,01-08-2024,NaN,Active
8,109,MOHIT,DELHI,hr,abc,2024/09/15,4.8,INACTIVE
9,110,Anjali,surat,Sales,45000,2024-10-05,4.1,active

In [3]:
#Convert name columns into title case and fill nan value 
new_data["Name"] = new_data["Name"].fillna("Unknown")
new_data["Name"] = new_data["Name"].str.title()

In [4]:
#City name convert to title case and fill nan value 
new_data["City"] = new_data["City"].fillna("Unknown")
new_data["City"] = new_data["City"].str.title()

In [5]:
#Department column convert propar formate 
new_data["Department"] = new_data["Department"].str.lower().fillna("Unknown")
new_data["Department"] = new_data["Department"].map({"sales":"Sales","it":"IT","hr":"HR"})

In [6]:
#Salary nan value fill
new_data["Salary"] = pd.to_numeric(new_data["Salary"],errors="coerce")
new_data["Salary"] = new_data["Salary"].fillna(new_data["Salary"].mean()).astype(int)

In [7]:
#Date convert propar form
new_data["Joining_Date"] = new_data["Joining_Date"].fillna(new_data["Joining_Date"].ffill())
new_data["Joining_Date"] = pd.to_datetime(new_data["Joining_Date"],format="mixed")
new_data["Joining_Date"] = new_data["Joining_Date"].dt.strftime("%d-%m-%Y")

In [8]:
#Performance Fill nan value
new_data["Performance"] = new_data["Performance"].fillna(new_data["Performance"].mean())

In [9]:
#Add new columns perfromance level 
def Performance_level(x):
    if x >= 4.5:
        return "Excellent"
    elif x >= 4.0:
        return "Good"
    else:
        return "Average"
new_data["Performance_level"] = new_data["Performance"].apply(Performance_level)

In [22]:
#Status column convert parfact form
new_data["Status"] = new_data["Status"].fillna("not").str.title()

In [23]:
new_data

,Employee_ID,Name,City,Department,Salary,Joining_Date,Performance,Status,Performance_level
0,101,Rahul,Ahmedabad,Sales,25000,15-01-2024,4.2000,Active,Good
1,102,Priya,Mumbai,Sales,30000,15-02-2024,3.8000,Active,Average
2,103,Amit,Delhi,IT,33750,10-03-2024,4.1125,Inactive,Good
3,104,Unknown,Ahmedabad,HR,28000,10-03-2024,4.5000,Active,Excellent
4,105,Neha,Unknown,Sales,35000,20-05-2024,4.0000,Not,Good
5,105,Neha,Ahmedabad,Sales,35000,20-05-2024,4.0000,Active,Good
6,107,Karan,Surat,NaN,40000,01-07-2024,3.5000,Inactive,Average
7,108,Riya,Mumbai,IT,32000,08-01-2024,4.1125,Active,Good
8,109,Mohit,Delhi,HR,33750,15-09-2024,4.8000,Inactive,Excellent
9,110,Anjali,Surat,Sales,45000,05-10-2024,4.1000,Active,Good