In [1]:
import pandas as pd

In [4]:
#Read excel file 
df = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\pandas_data_transformation_practice.csv")
df

   Employee_ID    Name Department  Salary  Experience  Join_Year
0         1005  Vivaan      Sales   45000           1       2023
1         1002    Diya         HR   52000           3       2021
2         1008    Myra  Marketing   58000           2       2022
3         1001   Aarav         IT   75000           6       2019
4         1006  Ishita         HR   49000           2       2022
5         1003   Rohan    Finance   62000           4       2020
6         1007  Aditya         IT   68000           5       2019
7         1004   Anaya         IT   70000           5       2018
8         1009   Arjun    Finance   60000           3       2021
9         1010   Kiara      Sales   50000           2       2023

In [5]:
#sort the dataframe by salary in ascending order 
df.sort_values("Salary",ascending=True)

   Employee_ID    Name Department  Salary  Experience  Join_Year
0         1005  Vivaan      Sales   45000           1       2023
4         1006  Ishita         HR   49000           2       2022
9         1010   Kiara      Sales   50000           2       2023
1         1002    Diya         HR   52000           3       2021
2         1008    Myra  Marketing   58000           2       2022
8         1009   Arjun    Finance   60000           3       2021
5         1003   Rohan    Finance   62000           4       2020
6         1007  Aditya         IT   68000           5       2019
7         1004   Anaya         IT   70000           5       2018
3         1001   Aarav         IT   75000           6       2019

In [6]:
#sort the dataframe by salary in descending order 
df.sort_values("Salary",ascending=False)

   Employee_ID    Name Department  Salary  Experience  Join_Year
3         1001   Aarav         IT   75000           6       2019
7         1004   Anaya         IT   70000           5       2018
6         1007  Aditya         IT   68000           5       2019
5         1003   Rohan    Finance   62000           4       2020
8         1009   Arjun    Finance   60000           3       2021
2         1008    Myra  Marketing   58000           2       2022
1         1002    Diya         HR   52000           3       2021
9         1010   Kiara      Sales   50000           2       2023
4         1006  Ishita         HR   49000           2       2022
0         1005  Vivaan      Sales   45000           1       2023

In [7]:
#Sort thge salary columns in descending order and make the change directly in the data frame 
df.sort_values("Salary",ascending=False,inplace=True)
df

   Employee_ID    Name Department  Salary  Experience  Join_Year
3         1001   Aarav         IT   75000           6       2019
7         1004   Anaya         IT   70000           5       2018
6         1007  Aditya         IT   68000           5       2019
5         1003   Rohan    Finance   62000           4       2020
8         1009   Arjun    Finance   60000           3       2021
2         1008    Myra  Marketing   58000           2       2022
1         1002    Diya         HR   52000           3       2021
9         1010   Kiara      Sales   50000           2       2023
4         1006  Ishita         HR   49000           2       2022
0         1005  Vivaan      Sales   45000           1       2023

In [8]:
#Sort the data frame index in ascending order 
df.reset_index(drop=True,inplace=True)
df

   Employee_ID    Name Department  Salary  Experience  Join_Year
0         1001   Aarav         IT   75000           6       2019
1         1004   Anaya         IT   70000           5       2018
2         1007  Aditya         IT   68000           5       2019
3         1003   Rohan    Finance   62000           4       2020
4         1009   Arjun    Finance   60000           3       2021
5         1008    Myra  Marketing   58000           2       2022
6         1002    Diya         HR   52000           3       2021
7         1010   Kiara      Sales   50000           2       2023
8         1006  Ishita         HR   49000           2       2022
9         1005  Vivaan      Sales   45000           1       2023

In [9]:
#Rename the salary column
df.rename(columns={"Salary":"Annual_Salary"},inplace=True)
df

   Employee_ID    Name Department  Annual_Salary  Experience  Join_Year
0         1001   Aarav         IT          75000           6       2019
1         1004   Anaya         IT          70000           5       2018
2         1007  Aditya         IT          68000           5       2019
3         1003   Rohan    Finance          62000           4       2020
4         1009   Arjun    Finance          60000           3       2021
5         1008    Myra  Marketing          58000           2       2022
6         1002    Diya         HR          52000           3       2021
7         1010   Kiara      Sales          50000           2       2023
8         1006  Ishita         HR          49000           2       2022
9         1005  Vivaan      Sales          45000           1       2023

In [10]:
#Rename Experience and Join_year 
df.rename(columns={"Experience":"Experience_Year","Join_Year":"Joining_Year"},inplace=True)
df

,Employee_ID,Name,Department,Annual_Salary,Experience_Year,Joining_Year
0,1001,Aarav,IT,75000,6,2019
1,1004,Anaya,IT,70000,5,2018
2,1007,Aditya,IT,68000,5,2019
3,1003,Rohan,Finance,62000,4,2020
4,1009,Arjun,Finance,60000,3,2021
5,1008,Myra,Marketing,58000,2,2022
6,1002,Diya,HR,52000,3,2021
7,1010,Kiara,Sales,50000,2,2023
8,1006,Ishita,HR,49000,2,2022
9,1005,Vivaan,Sales,45000,1,2023

In [11]:
#Multiple Column sorting department ascending and salary descending order 
df.sort_values(by=["Department","Annual_Salary"],ascending=[True,False])

,Employee_ID,Name,Department,Annual_Salary,Experience_Year,Joining_Year
3,1003,Rohan,Finance,62000,4,2020
4,1009,Arjun,Finance,60000,3,2021
6,1002,Diya,HR,52000,3,2021
8,1006,Ishita,HR,49000,2,2022
0,1001,Aarav,IT,75000,6,2019
1,1004,Anaya,IT,70000,5,2018
2,1007,Aditya,IT,68000,5,2019
5,1008,Myra,Marketing,58000,2,2022
7,1010,Kiara,Sales,50000,2,2023
9,1005,Vivaan,Sales,45000,1,2023

In [12]:
df.sort_values("Experience_Year",ascending=False)

,Employee_ID,Name,Department,Annual_Salary,Experience_Year,Joining_Year
0,1001,Aarav,IT,75000,6,2019
1,1004,Anaya,IT,70000,5,2018
2,1007,Aditya,IT,68000,5,2019
3,1003,Rohan,Finance,62000,4,2020
4,1009,Arjun,Finance,60000,3,2021
6,1002,Diya,HR,52000,3,2021
5,1008,Myra,Marketing,58000,2,2022
7,1010,Kiara,Sales,50000,2,2023
8,1006,Ishita,HR,49000,2,2022
9,1005,Vivaan,Sales,45000,1,2023

#New data set

In [60]:
data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\pandas_eda_sales_practice.csv")

In [61]:
data

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
1,O1002,2026-01-08,Priya,Mumbai,electronics,Mouse,5,800,5%,Card,4.0
2,O1003,2026-01-12,Amit,Delhi,Furniture,Chair,4,2500,0%,Cash,3.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10%,UPI,4.2
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15%,Card,4.8
5,O1006,2026-01-20,Riya,Mumbai,Clothing,Jeans,2,1800,10%,UPI,4.1
6,O1007,2026-01-23,Mohit,Delhi,Grocery,Rice,10,900,5%,Cash,3.9
7,O1008,2026-01-25,Anjali,Ahmedabad,Furniture,Table,1,6500,20%,Card,4.6
8,O1009,2026-01-28,Raj,Surat,Electronics,Headphones,3,2200,10%,UPI,4.3
9,O1010,2026-02-02,Simran,Mumbai,Clothing,T-Shirt,4,700,5%,Card,3.8
10,O1011,2026-02-05,Dev,Ahmedabad,electronics,Laptop,1,55000,10%,UPI,4.7
11,O1012,2026-02-08,Meena,Delhi,Furniture,Chair,8,2500,15%,Cash,4.0
12,O1013,2026-02-10,Arjun,Surat,Grocery,Wheat,12,600,0%,UPI,3.6
13,O1014,2026-02-14,Pooja,Ahmedabad,Clothing,Jeans,3,1800,10%,Card,4.4
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5%,UPI,4.5
15,O1016,2026-02-20,Sneha,Delhi,Grocery,Oil,5,1500,5%,Cash,3.7
16,O1017,2026-02-23,Varun,Ahmedabad,Furniture,Table,2,6500,10%,Card,4.2
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15%,UPI,4.6
18,O1019,2026-03-01,Yash,Mumbai,Electronics,Laptop,1,55000,10%,Card,4.9
19,O1020,2026-03-04,Tina,Ahmedabad,Grocery,Rice,7,900,5%,Cash,3.5
20,O1021,2026-03-07,Akash,Delhi,Electronics,Mouse,4,800,5%,UPI,4.1
21,O1022,2026-03-10,Isha,Surat,Furniture,Chair,3,2500,0%,Card,3.9
22,O1023,2026-03-13,Manish,Ahmedabad,Clothing,Jeans,2,1800,10%,UPI,4.3
23,O1024,2026-03-16,Kavya,Mumbai,Electronics,Headphones,2,2200,10%,Card,4.0
24,O1025,2026-03-20,NaN,Delhi,Grocery,Oil,6,1500,5%,Cash,3.6
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20%,UPI,4.5
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15%,Card,4.7
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10%,UPI,4.8
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5%,Cash,3.8
29,O1030,2026-04-02,Vikram,Delhi,Electronics,Keyboard,3,1500,10%,Card,4.2
30,O1010,2026-02-02,Simran,Mumbai,Clothing,T-Shirt,4,700,5%,Card,3.8

#Chack EDA

In [62]:
data.head()

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
1,O1002,2026-01-08,Priya,Mumbai,electronics,Mouse,5,800,5%,Card,4.0
2,O1003,2026-01-12,Amit,Delhi,Furniture,Chair,4,2500,0%,Cash,3.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10%,UPI,4.2
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15%,Card,4.8

In [63]:
data.tail()

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15%,Card,4.7
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10%,UPI,4.8
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5%,Cash,3.8
29,O1030,2026-04-02,Vikram,Delhi,Electronics,Keyboard,3,1500,10%,Card,4.2
30,O1010,2026-02-02,Simran,Mumbai,Clothing,T-Shirt,4,700,5%,Card,3.8

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    31 non-null     object
 1   Order_Date  31 non-null     object
 2   Customer    30 non-null     object
 3   City        31 non-null     object
 4   Category    31 non-null     object
 5   Product     31 non-null     object
 6   Quantity    31 non-null     int64
 7   Unit_Price  31 non-null     int64
 8   Discount    31 non-null     object
 9   Payment     31 non-null     object
 10  Rating      31 non-null     float64
dtypes: float64(1), int64(2), object(8)
memory usage: 2.8+ KB

In [65]:
data.describe()

        Quantity    Unit_Price     Rating
count  31.000000     31.000000  31.000000
mean    4.161290   9554.838710   4.177419
std     2.887869  18326.007725   0.412076
min     1.000000    600.000000   3.500000
25%     2.000000    850.000000   3.850000
50%     3.000000   1800.000000   4.200000
75%     5.500000   4500.000000   4.500000
max    12.000000  55000.000000   4.900000

In [66]:
data.columns

Index(['Order_ID', 'Order_Date', 'Customer', 'City', 'Category', 'Product',
       'Quantity', 'Unit_Price', 'Discount', 'Payment', 'Rating'],
      dtype='object')

In [67]:
data.shape

(31, 11)

In [68]:
#Chack total null value 
data.isnull().sum()

Order_ID      0
Order_Date    0
Customer      1
City          0
Category      0
Product       0
Quantity      0
Unit_Price    0
Discount      0
Payment       0
Rating        0
dtype: int64

In [69]:
#Chack duplicate row and drop duplicate row
data = data.drop_duplicates()
data

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
1,O1002,2026-01-08,Priya,Mumbai,electronics,Mouse,5,800,5%,Card,4.0
2,O1003,2026-01-12,Amit,Delhi,Furniture,Chair,4,2500,0%,Cash,3.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10%,UPI,4.2
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15%,Card,4.8
5,O1006,2026-01-20,Riya,Mumbai,Clothing,Jeans,2,1800,10%,UPI,4.1
6,O1007,2026-01-23,Mohit,Delhi,Grocery,Rice,10,900,5%,Cash,3.9
7,O1008,2026-01-25,Anjali,Ahmedabad,Furniture,Table,1,6500,20%,Card,4.6
8,O1009,2026-01-28,Raj,Surat,Electronics,Headphones,3,2200,10%,UPI,4.3
9,O1010,2026-02-02,Simran,Mumbai,Clothing,T-Shirt,4,700,5%,Card,3.8
10,O1011,2026-02-05,Dev,Ahmedabad,electronics,Laptop,1,55000,10%,UPI,4.7
11,O1012,2026-02-08,Meena,Delhi,Furniture,Chair,8,2500,15%,Cash,4.0
12,O1013,2026-02-10,Arjun,Surat,Grocery,Wheat,12,600,0%,UPI,3.6
13,O1014,2026-02-14,Pooja,Ahmedabad,Clothing,Jeans,3,1800,10%,Card,4.4
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5%,UPI,4.5
15,O1016,2026-02-20,Sneha,Delhi,Grocery,Oil,5,1500,5%,Cash,3.7
16,O1017,2026-02-23,Varun,Ahmedabad,Furniture,Table,2,6500,10%,Card,4.2
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15%,UPI,4.6
18,O1019,2026-03-01,Yash,Mumbai,Electronics,Laptop,1,55000,10%,Card,4.9
19,O1020,2026-03-04,Tina,Ahmedabad,Grocery,Rice,7,900,5%,Cash,3.5
20,O1021,2026-03-07,Akash,Delhi,Electronics,Mouse,4,800,5%,UPI,4.1
21,O1022,2026-03-10,Isha,Surat,Furniture,Chair,3,2500,0%,Card,3.9
22,O1023,2026-03-13,Manish,Ahmedabad,Clothing,Jeans,2,1800,10%,UPI,4.3
23,O1024,2026-03-16,Kavya,Mumbai,Electronics,Headphones,2,2200,10%,Card,4.0
24,O1025,2026-03-20,NaN,Delhi,Grocery,Oil,6,1500,5%,Cash,3.6
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20%,UPI,4.5
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15%,Card,4.7
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10%,UPI,4.8
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5%,Cash,3.8
29,O1030,2026-04-02,Vikram,Delhi,Electronics,Keyboard,3,1500,10%,Card,4.2

#Data selection & Filtering

In [70]:
#Print only customer,city, product columns 
data[["Customer","City","Product"]]

   Customer       City     Product
0     Rahul  Ahmedabad      Laptop
1     Priya     Mumbai       Mouse
2      Amit      Delhi       Chair
3      Neha  Ahmedabad    Keyboard
4     Karan      Surat     T-Shirt
5      Riya     Mumbai       Jeans
6     Mohit      Delhi        Rice
7    Anjali  Ahmedabad       Table
8       Raj      Surat  Headphones
9    Simran     Mumbai     T-Shirt
10      Dev  Ahmedabad      Laptop
11    Meena      Delhi       Chair
12    Arjun      Surat       Wheat
13    Pooja  Ahmedabad       Jeans
14    Rohan     Mumbai      Tablet
15    Sneha      Delhi         Oil
16    Varun  Ahmedabad       Table
17    Nisha      Surat     T-Shirt
18     Yash     Mumbai      Laptop
19     Tina  Ahmedabad        Rice
20    Akash      Delhi       Mouse
21     Isha      Surat       Chair
22   Manish  Ahmedabad       Jeans
23    Kavya     Mumbai  Headphones
24      NaN      Delhi         Oil
25    Rohit  Ahmedabad       Table
26    Priti      Surat     T-Shirt
27   Sameer     Mumbai      Laptop
28     Asha  Ahmedabad        Rice
29   Vikram      Delhi    Keyboard

In [71]:
#Only print ahmedabad order 
data[(data["City"] == "Ahmedabad")]

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10%,UPI,4.2
7,O1008,2026-01-25,Anjali,Ahmedabad,Furniture,Table,1,6500,20%,Card,4.6
10,O1011,2026-02-05,Dev,Ahmedabad,electronics,Laptop,1,55000,10%,UPI,4.7
13,O1014,2026-02-14,Pooja,Ahmedabad,Clothing,Jeans,3,1800,10%,Card,4.4
16,O1017,2026-02-23,Varun,Ahmedabad,Furniture,Table,2,6500,10%,Card,4.2
19,O1020,2026-03-04,Tina,Ahmedabad,Grocery,Rice,7,900,5%,Cash,3.5
22,O1023,2026-03-13,Manish,Ahmedabad,Clothing,Jeans,2,1800,10%,UPI,4.3
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20%,UPI,4.5
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5%,Cash,3.8

In [72]:
#Print only 5 to up quantity order 
data[(data["Quantity"] >= 5)]

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
1,O1002,2026-01-08,Priya,Mumbai,electronics,Mouse,5,800,5%,Card,4.0
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15%,Card,4.8
6,O1007,2026-01-23,Mohit,Delhi,Grocery,Rice,10,900,5%,Cash,3.9
11,O1012,2026-02-08,Meena,Delhi,Furniture,Chair,8,2500,15%,Cash,4.0
12,O1013,2026-02-10,Arjun,Surat,Grocery,Wheat,12,600,0%,UPI,3.6
15,O1016,2026-02-20,Sneha,Delhi,Grocery,Oil,5,1500,5%,Cash,3.7
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15%,UPI,4.6
19,O1020,2026-03-04,Tina,Ahmedabad,Grocery,Rice,7,900,5%,Cash,3.5
24,O1025,2026-03-20,NaN,Delhi,Grocery,Oil,6,1500,5%,Cash,3.6
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15%,Card,4.7
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5%,Cash,3.8

In [73]:
#Only 10000 up price order print 
data[(data["Unit_Price"] > 10000)]

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
10,O1011,2026-02-05,Dev,Ahmedabad,electronics,Laptop,1,55000,10%,UPI,4.7
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5%,UPI,4.5
18,O1019,2026-03-01,Yash,Mumbai,Electronics,Laptop,1,55000,10%,Card,4.9
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10%,UPI,4.8

In [74]:
#Electronics + Ahmedabad order print 
# data[(data["Category"] == "Electronics") & (data["City"] == "Ahmedabad")]
data.query("Category == 'Electronics' and City == 'Ahmedabad'")   #Two method

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10%,UPI,4.2

In [75]:
#Only print 4.5 up rating customert 
# data[(data["Rating"] >= 4.5)]
data.query("Rating >= 4.5")

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15%,Card,4.8
7,O1008,2026-01-25,Anjali,Ahmedabad,Furniture,Table,1,6500,20%,Card,4.6
10,O1011,2026-02-05,Dev,Ahmedabad,electronics,Laptop,1,55000,10%,UPI,4.7
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5%,UPI,4.5
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15%,UPI,4.6
18,O1019,2026-03-01,Yash,Mumbai,Electronics,Laptop,1,55000,10%,Card,4.9
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20%,UPI,4.5
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15%,Card,4.7
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10%,UPI,4.8

In [76]:
#Only print UPI payment customert
data.query("Payment == 'UPI'")

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10%,UPI,4.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10%,UPI,4.2
5,O1006,2026-01-20,Riya,Mumbai,Clothing,Jeans,2,1800,10%,UPI,4.1
8,O1009,2026-01-28,Raj,Surat,Electronics,Headphones,3,2200,10%,UPI,4.3
10,O1011,2026-02-05,Dev,Ahmedabad,electronics,Laptop,1,55000,10%,UPI,4.7
12,O1013,2026-02-10,Arjun,Surat,Grocery,Wheat,12,600,0%,UPI,3.6
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5%,UPI,4.5
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15%,UPI,4.6
20,O1021,2026-03-07,Akash,Delhi,Electronics,Mouse,4,800,5%,UPI,4.1
22,O1023,2026-03-13,Manish,Ahmedabad,Clothing,Jeans,2,1800,10%,UPI,4.3
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20%,UPI,4.5
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10%,UPI,4.8

#Data cleaning preprocessing

In [90]:
#Fill missing customer name 
data = data.copy()
data["Customer"] = data["Customer"].fillna("Unknown")
data

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10,UPI,4.5
1,O1002,2026-01-08,Priya,Mumbai,Electronics,Mouse,5,800,5,Card,4.0
2,O1003,2026-01-12,Amit,Delhi,Furniture,Chair,4,2500,0,Cash,3.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10,UPI,4.2
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15,Card,4.8
5,O1006,2026-01-20,Riya,Mumbai,Clothing,Jeans,2,1800,10,UPI,4.1
6,O1007,2026-01-23,Mohit,Delhi,Grocery,Rice,10,900,5,Cash,3.9
7,O1008,2026-01-25,Anjali,Ahmedabad,Furniture,Table,1,6500,20,Card,4.6
8,O1009,2026-01-28,Raj,Surat,Electronics,Headphones,3,2200,10,UPI,4.3
9,O1010,2026-02-02,Simran,Mumbai,Clothing,T-Shirt,4,700,5,Card,3.8
10,O1011,2026-02-05,Dev,Ahmedabad,Electronics,Laptop,1,55000,10,UPI,4.7
11,O1012,2026-02-08,Meena,Delhi,Furniture,Chair,8,2500,15,Cash,4.0
12,O1013,2026-02-10,Arjun,Surat,Grocery,Wheat,12,600,0,UPI,3.6
13,O1014,2026-02-14,Pooja,Ahmedabad,Clothing,Jeans,3,1800,10,Card,4.4
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5,UPI,4.5
15,O1016,2026-02-20,Sneha,Delhi,Grocery,Oil,5,1500,5,Cash,3.7
16,O1017,2026-02-23,Varun,Ahmedabad,Furniture,Table,2,6500,10,Card,4.2
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15,UPI,4.6
18,O1019,2026-03-01,Yash,Mumbai,Electronics,Laptop,1,55000,10,Card,4.9
19,O1020,2026-03-04,Tina,Ahmedabad,Grocery,Rice,7,900,5,Cash,3.5
20,O1021,2026-03-07,Akash,Delhi,Electronics,Mouse,4,800,5,UPI,4.1
21,O1022,2026-03-10,Isha,Surat,Furniture,Chair,3,2500,0,Card,3.9
22,O1023,2026-03-13,Manish,Ahmedabad,Clothing,Jeans,2,1800,10,UPI,4.3
23,O1024,2026-03-16,Kavya,Mumbai,Electronics,Headphones,2,2200,10,Card,4.0
24,O1025,2026-03-20,Unknown,Delhi,Grocery,Oil,6,1500,5,Cash,3.6
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20,UPI,4.5
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15,Card,4.7
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10,UPI,4.8
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5,Cash,3.8
29,O1030,2026-04-02,Vikram,Delhi,Electronics,Keyboard,3,1500,10,Card,4.2

In [91]:
#change electronics to Electronics
data["Category"] = data["Category"].replace({"electronics":"Electronics"})
data

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10,UPI,4.5
1,O1002,2026-01-08,Priya,Mumbai,Electronics,Mouse,5,800,5,Card,4.0
2,O1003,2026-01-12,Amit,Delhi,Furniture,Chair,4,2500,0,Cash,3.5
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10,UPI,4.2
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15,Card,4.8
5,O1006,2026-01-20,Riya,Mumbai,Clothing,Jeans,2,1800,10,UPI,4.1
6,O1007,2026-01-23,Mohit,Delhi,Grocery,Rice,10,900,5,Cash,3.9
7,O1008,2026-01-25,Anjali,Ahmedabad,Furniture,Table,1,6500,20,Card,4.6
8,O1009,2026-01-28,Raj,Surat,Electronics,Headphones,3,2200,10,UPI,4.3
9,O1010,2026-02-02,Simran,Mumbai,Clothing,T-Shirt,4,700,5,Card,3.8
10,O1011,2026-02-05,Dev,Ahmedabad,Electronics,Laptop,1,55000,10,UPI,4.7
11,O1012,2026-02-08,Meena,Delhi,Furniture,Chair,8,2500,15,Cash,4.0
12,O1013,2026-02-10,Arjun,Surat,Grocery,Wheat,12,600,0,UPI,3.6
13,O1014,2026-02-14,Pooja,Ahmedabad,Clothing,Jeans,3,1800,10,Card,4.4
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5,UPI,4.5
15,O1016,2026-02-20,Sneha,Delhi,Grocery,Oil,5,1500,5,Cash,3.7
16,O1017,2026-02-23,Varun,Ahmedabad,Furniture,Table,2,6500,10,Card,4.2
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15,UPI,4.6
18,O1019,2026-03-01,Yash,Mumbai,Electronics,Laptop,1,55000,10,Card,4.9
19,O1020,2026-03-04,Tina,Ahmedabad,Grocery,Rice,7,900,5,Cash,3.5
20,O1021,2026-03-07,Akash,Delhi,Electronics,Mouse,4,800,5,UPI,4.1
21,O1022,2026-03-10,Isha,Surat,Furniture,Chair,3,2500,0,Card,3.9
22,O1023,2026-03-13,Manish,Ahmedabad,Clothing,Jeans,2,1800,10,UPI,4.3
23,O1024,2026-03-16,Kavya,Mumbai,Electronics,Headphones,2,2200,10,Card,4.0
24,O1025,2026-03-20,Unknown,Delhi,Grocery,Oil,6,1500,5,Cash,3.6
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20,UPI,4.5
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15,Card,4.7
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10,UPI,4.8
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5,Cash,3.8
29,O1030,2026-04-02,Vikram,Delhi,Electronics,Keyboard,3,1500,10,Card,4.2

In [95]:
#Order data convert datetime 
data["Order_Date"] = pd.to_datetime(data["Order_Date"])

#Data transformation

In [118]:
#New create columns name Total sales 
data["Total_sales"] = data["Quantity"] * data["Unit_Price"]
data

,Order_ID,Order_Date,Customer,City,Category,Product,Quantity,Unit_Price,Discount,Payment,Rating,Total_sales
0,O1001,2026-01-05,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10,UPI,4.5,110000
1,O1002,2026-01-08,Priya,Mumbai,Electronics,Mouse,5,800,5,Card,4.0,4000
2,O1003,2026-01-12,Amit,Delhi,Furniture,Chair,4,2500,0,Cash,3.5,10000
3,O1004,2026-01-15,Neha,Ahmedabad,Electronics,Keyboard,3,1500,10,UPI,4.2,4500
4,O1005,2026-01-18,Karan,Surat,Clothing,T-Shirt,6,700,15,Card,4.8,4200
5,O1006,2026-01-20,Riya,Mumbai,Clothing,Jeans,2,1800,10,UPI,4.1,3600
6,O1007,2026-01-23,Mohit,Delhi,Grocery,Rice,10,900,5,Cash,3.9,9000
7,O1008,2026-01-25,Anjali,Ahmedabad,Furniture,Table,1,6500,20,Card,4.6,6500
8,O1009,2026-01-28,Raj,Surat,Electronics,Headphones,3,2200,10,UPI,4.3,6600
9,O1010,2026-02-02,Simran,Mumbai,Clothing,T-Shirt,4,700,5,Card,3.8,2800
10,O1011,2026-02-05,Dev,Ahmedabad,Electronics,Laptop,1,55000,10,UPI,4.7,55000
11,O1012,2026-02-08,Meena,Delhi,Furniture,Chair,8,2500,15,Cash,4.0,20000
12,O1013,2026-02-10,Arjun,Surat,Grocery,Wheat,12,600,0,UPI,3.6,7200
13,O1014,2026-02-14,Pooja,Ahmedabad,Clothing,Jeans,3,1800,10,Card,4.4,5400
14,O1015,2026-02-17,Rohan,Mumbai,Electronics,Tablet,2,25000,5,UPI,4.5,50000
15,O1016,2026-02-20,Sneha,Delhi,Grocery,Oil,5,1500,5,Cash,3.7,7500
16,O1017,2026-02-23,Varun,Ahmedabad,Furniture,Table,2,6500,10,Card,4.2,13000
17,O1018,2026-02-26,Nisha,Surat,Clothing,T-Shirt,5,700,15,UPI,4.6,3500
18,O1019,2026-03-01,Yash,Mumbai,Electronics,Laptop,1,55000,10,Card,4.9,55000
19,O1020,2026-03-04,Tina,Ahmedabad,Grocery,Rice,7,900,5,Cash,3.5,6300
20,O1021,2026-03-07,Akash,Delhi,Electronics,Mouse,4,800,5,UPI,4.1,3200
21,O1022,2026-03-10,Isha,Surat,Furniture,Chair,3,2500,0,Card,3.9,7500
22,O1023,2026-03-13,Manish,Ahmedabad,Clothing,Jeans,2,1800,10,UPI,4.3,3600
23,O1024,2026-03-16,Kavya,Mumbai,Electronics,Headphones,2,2200,10,Card,4.0,4400
24,O1025,2026-03-20,Unknown,Delhi,Grocery,Oil,6,1500,5,Cash,3.6,9000
25,O1026,2026-03-22,Rohit,Ahmedabad,Furniture,Table,1,6500,20,UPI,4.5,6500
26,O1027,2026-03-25,Priti,Surat,Clothing,T-Shirt,8,700,15,Card,4.7,5600
27,O1028,2026-03-28,Sameer,Mumbai,Electronics,Laptop,1,55000,10,UPI,4.8,55000
28,O1029,2026-03-30,Asha,Ahmedabad,Grocery,Rice,9,900,5,Cash,3.8,8100
29,O1030,2026-04-02,Vikram,Delhi,Electronics,Keyboard,3,1500,10,Card,4.2,4500