In [1]:
import numpy as np
import pandas as pd

In [2]:
df =  pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\employee_data.csv")
df

   EmpID          Name Department  Age  Salary       City  JoinYear
0    101  Rahul Sharma      Sales   29   45000      Delhi      2019
1    102   Priya Singh         IT   34   72000     Mumbai      2017
2    103    Amit Verma      Sales   25   39000      Delhi      2021
3    104    Neha Gupta         HR   41   55000       Pune      2015
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
5    106   Sneha Joshi         HR   25   42000    Chennai      2021
6    107   Karan Mehta      Sales   34   51000      Delhi      2018
7    108   Anjali Nair         IT   41   80000  Bangalore      2014
8    109     Rohan Das         HR   29   47000       Pune      2019
9    110   Isha Kapoor         IT   25   60000  Bangalore      2022

In [3]:
#Print the first 5 rows 
df.head()

   EmpID          Name Department  Age  Salary    City  JoinYear
0    101  Rahul Sharma      Sales   29   45000   Delhi      2019
1    102   Priya Singh         IT   34   72000  Mumbai      2017
2    103    Amit Verma      Sales   25   39000   Delhi      2021
3    104    Neha Gupta         HR   41   55000    Pune      2015
4    105    Vikram Rao         IT   29   68000  Mumbai      2020

In [4]:
#Sort the salary in descending order 
df.sort_values("Salary",ascending=False)

   EmpID          Name Department  Age  Salary       City  JoinYear
7    108   Anjali Nair         IT   41   80000  Bangalore      2014
1    102   Priya Singh         IT   34   72000     Mumbai      2017
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
9    110   Isha Kapoor         IT   25   60000  Bangalore      2022
3    104    Neha Gupta         HR   41   55000       Pune      2015
6    107   Karan Mehta      Sales   34   51000      Delhi      2018
8    109     Rohan Das         HR   29   47000       Pune      2019
0    101  Rahul Sharma      Sales   29   45000      Delhi      2019
5    106   Sneha Joshi         HR   25   42000    Chennai      2021
2    103    Amit Verma      Sales   25   39000      Delhi      2021

In [5]:
#Sort department (ascendingorder) and age (descendingorder)
df.sort_values(["Department","Age"],ascending=[True,False])

   EmpID          Name Department  Age  Salary       City  JoinYear
3    104    Neha Gupta         HR   41   55000       Pune      2015
8    109     Rohan Das         HR   29   47000       Pune      2019
5    106   Sneha Joshi         HR   25   42000    Chennai      2021
7    108   Anjali Nair         IT   41   80000  Bangalore      2014
1    102   Priya Singh         IT   34   72000     Mumbai      2017
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
9    110   Isha Kapoor         IT   25   60000  Bangalore      2022
6    107   Karan Mehta      Sales   34   51000      Delhi      2018
0    101  Rahul Sharma      Sales   29   45000      Delhi      2019
2    103    Amit Verma      Sales   25   39000      Delhi      2021

In [6]:
#Sort age is ascendingorder and reset index and drop old index 
df.sort_values("Age",ascending=True).reset_index(drop=True)

   EmpID          Name Department  Age  Salary       City  JoinYear
0    103    Amit Verma      Sales   25   39000      Delhi      2021
1    106   Sneha Joshi         HR   25   42000    Chennai      2021
2    110   Isha Kapoor         IT   25   60000  Bangalore      2022
3    101  Rahul Sharma      Sales   29   45000      Delhi      2019
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
5    109     Rohan Das         HR   29   47000       Pune      2019
6    102   Priya Singh         IT   34   72000     Mumbai      2017
7    107   Karan Mehta      Sales   34   51000      Delhi      2018
8    104    Neha Gupta         HR   41   55000       Pune      2015
9    108   Anjali Nair         IT   41   80000  Bangalore      2014

In [7]:
#Sort by salary descendingorder and change orignal data set 
df.sort_values("Salary",ascending=False,inplace=True)
df

   EmpID          Name Department  Age  Salary       City  JoinYear
7    108   Anjali Nair         IT   41   80000  Bangalore      2014
1    102   Priya Singh         IT   34   72000     Mumbai      2017
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
9    110   Isha Kapoor         IT   25   60000  Bangalore      2022
3    104    Neha Gupta         HR   41   55000       Pune      2015
6    107   Karan Mehta      Sales   34   51000      Delhi      2018
8    109     Rohan Das         HR   29   47000       Pune      2019
0    101  Rahul Sharma      Sales   29   45000      Delhi      2019
5    106   Sneha Joshi         HR   25   42000    Chennai      2021
2    103    Amit Verma      Sales   25   39000      Delhi      2021

In [8]:
#Reorder the columns first name,age,department ,salary ..
df[["Name","Age","EmpID","Department","Salary","City","JoinYear"]]

           Name  Age  EmpID Department  Salary       City  JoinYear
7   Anjali Nair   41    108         IT   80000  Bangalore      2014
1   Priya Singh   34    102         IT   72000     Mumbai      2017
4    Vikram Rao   29    105         IT   68000     Mumbai      2020
9   Isha Kapoor   25    110         IT   60000  Bangalore      2022
3    Neha Gupta   41    104         HR   55000       Pune      2015
6   Karan Mehta   34    107      Sales   51000      Delhi      2018
8     Rohan Das   29    109         HR   47000       Pune      2019
0  Rahul Sharma   29    101      Sales   45000      Delhi      2019
5   Sneha Joshi   25    106         HR   42000    Chennai      2021
2    Amit Verma   25    103      Sales   39000      Delhi      2021

In [9]:
#Rename Column name 
df.rename(columns={"EmpID":"Employee_ID","JoinYear":"Year_Joined"})

   Employee_ID          Name Department  Age  Salary       City  Year_Joined
7          108   Anjali Nair         IT   41   80000  Bangalore         2014
1          102   Priya Singh         IT   34   72000     Mumbai         2017
4          105    Vikram Rao         IT   29   68000     Mumbai         2020
9          110   Isha Kapoor         IT   25   60000  Bangalore         2022
3          104    Neha Gupta         HR   41   55000       Pune         2015
6          107   Karan Mehta      Sales   34   51000      Delhi         2018
8          109     Rohan Das         HR   29   47000       Pune         2019
0          101  Rahul Sharma      Sales   29   45000      Delhi         2019
5          106   Sneha Joshi         HR   25   42000    Chennai         2021
2          103    Amit Verma      Sales   25   39000      Delhi         2021

In [10]:
#Sort by city ascending and salary ascending then reset index 
df.sort_values(["City","Salary"],ascending=[True,True]).reset_index(drop=True)

   EmpID          Name Department  Age  Salary       City  JoinYear
0    110   Isha Kapoor         IT   25   60000  Bangalore      2022
1    108   Anjali Nair         IT   41   80000  Bangalore      2014
2    106   Sneha Joshi         HR   25   42000    Chennai      2021
3    103    Amit Verma      Sales   25   39000      Delhi      2021
4    101  Rahul Sharma      Sales   29   45000      Delhi      2019
5    107   Karan Mehta      Sales   34   51000      Delhi      2018
6    105    Vikram Rao         IT   29   68000     Mumbai      2020
7    102   Priya Singh         IT   34   72000     Mumbai      2017
8    109     Rohan Das         HR   29   47000       Pune      2019
9    104    Neha Gupta         HR   41   55000       Pune      2015

In [11]:
#Find the top 3 highest paid employess 
df.sort_values("Salary",ascending=False).head(3)

   EmpID         Name Department  Age  Salary       City  JoinYear
7    108  Anjali Nair         IT   41   80000  Bangalore      2014
1    102  Priya Singh         IT   34   72000     Mumbai      2017
4    105   Vikram Rao         IT   29   68000     Mumbai      2020

In [12]:
#Sort by multiple columns department (ascending),age(ascending),salary(descending)
df.sort_values(by=["Department","Age","Salary"],ascending=[True,True,False])

   EmpID          Name Department  Age  Salary       City  JoinYear
5    106   Sneha Joshi         HR   25   42000    Chennai      2021
8    109     Rohan Das         HR   29   47000       Pune      2019
3    104    Neha Gupta         HR   41   55000       Pune      2015
9    110   Isha Kapoor         IT   25   60000  Bangalore      2022
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
1    102   Priya Singh         IT   34   72000     Mumbai      2017
7    108   Anjali Nair         IT   41   80000  Bangalore      2014
2    103    Amit Verma      Sales   25   39000      Delhi      2021
0    101  Rahul Sharma      Sales   29   45000      Delhi      2019
6    107   Karan Mehta      Sales   34   51000      Delhi      2018

#This data convert proper format

In [13]:
data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\employee_data.csv")
data

   EmpID          Name Department  Age  Salary       City  JoinYear
0    101  Rahul Sharma      Sales   29   45000      Delhi      2019
1    102   Priya Singh         IT   34   72000     Mumbai      2017
2    103    Amit Verma      Sales   25   39000      Delhi      2021
3    104    Neha Gupta         HR   41   55000       Pune      2015
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
5    106   Sneha Joshi         HR   25   42000    Chennai      2021
6    107   Karan Mehta      Sales   34   51000      Delhi      2018
7    108   Anjali Nair         IT   41   80000  Bangalore      2014
8    109     Rohan Das         HR   29   47000       Pune      2019
9    110   Isha Kapoor         IT   25   60000  Bangalore      2022

In [34]:
#Sort Department and Salary and descending 
data.sort_values(["Department","Salary","JoinYear"],ascending=[False,False,False],inplace=True)

In [35]:
data

   EmpID          Name Department  Age  Salary       City  JoinYear
6    107   Karan Mehta      Sales   34   51000      Delhi      2018
0    101  Rahul Sharma      Sales   29   45000      Delhi      2019
2    103    Amit Verma      Sales   25   39000      Delhi      2021
7    108   Anjali Nair         IT   41   80000  Bangalore      2014
1    102   Priya Singh         IT   34   72000     Mumbai      2017
4    105    Vikram Rao         IT   29   68000     Mumbai      2020
9    110   Isha Kapoor         IT   25   60000  Bangalore      2022
3    104    Neha Gupta         HR   41   55000       Pune      2015
8    109     Rohan Das         HR   29   47000       Pune      2019
5    106   Sneha Joshi         HR   25   42000    Chennai      2021

In [39]:
#Sort index and drop old index
data.reset_index(drop=True,inplace=True)

In [40]:
#Rename columns 
data.rename(columns={"EmpID":"Employee_ID","JoinYear":"Year_Of_Joining"},inplace=True)

In [42]:
#Reorder columns in proper
data[["Employee_ID","Name","Department","City","Age","Salary","Year_Of_Joining"]]

,Employee_ID,Name,Department,City,Age,Salary,Year_Of_Joining
0,107,Karan Mehta,Sales,Delhi,34,51000,2018
1,101,Rahul Sharma,Sales,Delhi,29,45000,2019
2,103,Amit Verma,Sales,Delhi,25,39000,2021
3,108,Anjali Nair,IT,Bangalore,41,80000,2014
4,102,Priya Singh,IT,Mumbai,34,72000,2017
5,105,Vikram Rao,IT,Mumbai,29,68000,2020
6,110,Isha Kapoor,IT,Bangalore,25,60000,2022
7,104,Neha Gupta,HR,Pune,41,55000,2015
8,109,Rohan Das,HR,Pune,29,47000,2019
9,106,Sneha Joshi,HR,Chennai,25,42000,2021

In [49]:
#Name and city convert propar title case 
data["Name"] = data["Name"].str.title()
data["City"] = data["City"].str.title()

In [54]:
data

,Employee_ID,Name,Department,Age,Salary,City,Year_Of_Joining
0,107,Karan Mehta,Sales,34,51000,Delhi,2018
1,101,Rahul Sharma,Sales,29,45000,Delhi,2019
2,103,Amit Verma,Sales,25,39000,Delhi,2021
3,108,Anjali Nair,IT,41,80000,Bangalore,2014
4,102,Priya Singh,IT,34,72000,Mumbai,2017
5,105,Vikram Rao,IT,29,68000,Mumbai,2020
6,110,Isha Kapoor,IT,25,60000,Bangalore,2022
7,104,Neha Gupta,HR,41,55000,Pune,2015
8,109,Rohan Das,HR,29,47000,Pune,2019
9,106,Sneha Joshi,HR,25,42000,Chennai,2021