In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\Sales_Pandas_Practice_Dataset.csv")

In [4]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2.0,55000,2024-01-10,10.0,paid
1,1002,PRIYA,MUMBAI,electronics,Mobile,5.0,15000,15/02/2024,5.0,PAID
2,1003,Amit,Delhi,Furniture,Chair,3.0,7000,2024-03-05,NaN,pending
3,1004,NaN,Surat,Clothing,Shirt,NaN,2500,NaN,0.0,Paid
4,1005,Neha,NaN,Grocery,Rice,10.0,80,2024-05-20,2.0,NaN
5,1006,Neha,Ahmedabad,NaN,Tablet,1.0,20000,2024-06-15,5.0,paid
6,1006,Neha,Ahmedabad,Electronics,Tablet,1.0,20000,2024-06-15,5.0,paid
7,1008,Karan,SURAT,Clothing,Jeans,4.0,3000,01-08-2024,3.0,pending
8,1009,MOHIT,Delhi,FURNITURE,Table,2.0,9000,2024/09/10,10.0,PENDING
9,1010,Anjali,Mumbai,Electronics,Laptop,3.0,55000,2024-10-01,8.0,paid

#Chack Besic EDA

In [5]:
#Chack the shape of the date set 
data.shape    #10 rows and 10 columns

(10, 10)

In [6]:
#Chack columns name 
data.columns

Index(['Order_ID', 'Customer', 'City', 'Category', 'Product', 'Quantity',
       'Price', 'Order_Date', 'Discount', 'Payment_Status'],
      dtype='object')

In [7]:
#Chack besic information of the data set 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10 non-null     int64
 1   Customer        9 non-null      object
 2   City            9 non-null      object
 3   Category        9 non-null      object
 4   Product         10 non-null     object
 5   Quantity        9 non-null      float64
 6   Price           10 non-null     int64
 7   Order_Date      9 non-null      object
 8   Discount        9 non-null      float64
 9   Payment_Status  9 non-null      object
dtypes: float64(2), int64(2), object(6)
memory usage: 932.0+ bytes

In [8]:
#Chack besic numeric calculation 
data.describe()

          Order_ID   Quantity        Price   Discount
count    10.000000   9.000000     10.00000   9.000000
mean   1005.400000   3.444444  18658.00000   5.333333
std       2.988868   2.788867  20382.58178   3.464102
min    1001.000000   1.000000     80.00000   0.000000
25%    1003.250000   2.000000   4000.00000   3.000000
50%    1005.500000   3.000000  12000.00000   5.000000
75%    1007.500000   4.000000  20000.00000   8.000000
max    1010.000000  10.000000  55000.00000  10.000000

In [9]:
#Find missing values in every columns 
data.isnull().sum()

Order_ID          0
Customer          1
City              1
Category          1
Product           0
Quantity          1
Price             0
Order_Date        1
Discount          1
Payment_Status    1
dtype: int64

#Handle all missing value

In [10]:
#Fill customer missing value 
data["Customer"] = data["Customer"].fillna("Unknown")

In [11]:
#Fill missing city name 
data["City"] = data["City"].fillna("Unknwon")

In [12]:
#Fill most frequent value of  missing Category 
data["Category"].value_counts()

Category
Electronics    3
Clothing       2
electronics    1
Furniture      1
Grocery        1
FURNITURE      1
Name: count, dtype: int64

In [13]:
data["Category"] = data["Category"].fillna(data["Category"].mode()[0])

In [14]:
#fill missing quantity value 
data["Quantity"] = data["Quantity"].fillna(data["Quantity"].median())

In [15]:
#Fill missing discount value 
data["Discount"] = data["Discount"].fillna(0)

In [16]:
#Fill missing date 
data["Order_Date"] = data["Order_Date"].ffill()

In [17]:
#Fill missing Payment_status 
data["Payment_Status"] = data["Payment_Status"].fillna("Unknown")

In [18]:
#Chack all missing value 
data.isnull().sum()   #All missing value fill

Order_ID          0
Customer          0
City              0
Category          0
Product           0
Quantity          0
Price             0
Order_Date        0
Discount          0
Payment_Status    0
dtype: int64

In [19]:
#Remove duplicate data 
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [20]:
#Drop duplicate value 
data = data.drop_duplicates().copy()

In [21]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2.0,55000,2024-01-10,10.0,paid
1,1002,PRIYA,MUMBAI,electronics,Mobile,5.0,15000,15/02/2024,5.0,PAID
2,1003,Amit,Delhi,Furniture,Chair,3.0,7000,2024-03-05,0.0,pending
3,1004,Unknown,Surat,Clothing,Shirt,3.0,2500,2024-03-05,0.0,Paid
4,1005,Neha,Unknwon,Grocery,Rice,10.0,80,2024-05-20,2.0,Unknown
5,1006,Neha,Ahmedabad,Electronics,Tablet,1.0,20000,2024-06-15,5.0,paid
7,1008,Karan,SURAT,Clothing,Jeans,4.0,3000,01-08-2024,3.0,pending
8,1009,MOHIT,Delhi,FURNITURE,Table,2.0,9000,2024/09/10,10.0,PENDING
9,1010,Anjali,Mumbai,Electronics,Laptop,3.0,55000,2024-10-01,8.0,paid

#Remove extra spaces from text columns

In [22]:
#Remove customer columns extra space 
data["Customer"] = data["Customer"].str.strip()

In [23]:
#Remove City columns extra space 
data["City"] = data["City"].str.strip()

In [24]:
#Remove Category columns extra space 
data["Category"] = data["Category"].str.strip()

In [25]:
#Remove customer columns extra space 
data["Product"] = data["Product"].str.strip()

In [26]:
#Remove Payment_Status columns extra space 
data["Payment_Status"] = data["Payment_Status"].str.strip()

#Convert text columns into proper format

In [27]:
#Customer name columns convert title case
data["Customer"] = data["Customer"].str.title()

In [28]:
#City name columns convert title case
data["City"] = data["City"].str.title()

In [29]:
#Category name columns convert title case 
data["Category"] = data["Category"].str.title()

#Date clean and convert propar date

In [101]:
data["Order_Date"] = pd.to_datetime(data["Order_Date"],format="mixed",dayfirst=True).dt.strftime("%d-%m-%Y")

In [102]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status,Total_Amount,Order_size
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10-01-2024,10.0,Paid,110000,Big order
1,1002,Priya,Mumbai,Electronics,Mobile,5,15000,15-02-2024,5.0,Paid,75000,Big order
2,1003,Amit,Delhi,Furniture,Chair,3,7000,05-03-2024,0.0,Pending,21000,Normal order
3,1004,Unknown,Surat,Clothing,Shirt,3,2500,05-03-2024,0.0,Paid,7500,Normal order
4,1005,Neha,Unknwon,Grocery,Rice,10,80,20-05-2024,2.0,Unknown,800,Normal order
5,1006,Neha,Ahmedabad,Electronics,Tablet,1,20000,15-06-2024,5.0,Paid,20000,Normal order
7,1008,Karan,Surat,Clothing,Jeans,4,3000,01-08-2024,3.0,Pending,12000,Normal order
8,1009,Mohit,Delhi,Furniture,Table,2,9000,10-09-2024,10.0,Pending,18000,Normal order
9,1010,Anjali,Mumbai,Electronics,Laptop,3,55000,01-10-2024,8.0,Paid,165000,Big order

In [103]:
#Quentity column  convert integer form
data["Quantity"] = data["Quantity"].astype(int)

In [104]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status,Total_Amount,Order_size
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10-01-2024,10.0,Paid,110000,Big order
1,1002,Priya,Mumbai,Electronics,Mobile,5,15000,15-02-2024,5.0,Paid,75000,Big order
2,1003,Amit,Delhi,Furniture,Chair,3,7000,05-03-2024,0.0,Pending,21000,Normal order
3,1004,Unknown,Surat,Clothing,Shirt,3,2500,05-03-2024,0.0,Paid,7500,Normal order
4,1005,Neha,Unknwon,Grocery,Rice,10,80,20-05-2024,2.0,Unknown,800,Normal order
5,1006,Neha,Ahmedabad,Electronics,Tablet,1,20000,15-06-2024,5.0,Paid,20000,Normal order
7,1008,Karan,Surat,Clothing,Jeans,4,3000,01-08-2024,3.0,Pending,12000,Normal order
8,1009,Mohit,Delhi,Furniture,Table,2,9000,10-09-2024,10.0,Pending,18000,Normal order
9,1010,Anjali,Mumbai,Electronics,Laptop,3,55000,01-10-2024,8.0,Paid,165000,Big order

In [105]:
#Create total amount column
data["Total_Amount"] = data["Price"] * data["Quantity"]
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status,Total_Amount,Order_size
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10-01-2024,10.0,Paid,110000,Big order
1,1002,Priya,Mumbai,Electronics,Mobile,5,15000,15-02-2024,5.0,Paid,75000,Big order
2,1003,Amit,Delhi,Furniture,Chair,3,7000,05-03-2024,0.0,Pending,21000,Normal order
3,1004,Unknown,Surat,Clothing,Shirt,3,2500,05-03-2024,0.0,Paid,7500,Normal order
4,1005,Neha,Unknwon,Grocery,Rice,10,80,20-05-2024,2.0,Unknown,800,Normal order
5,1006,Neha,Ahmedabad,Electronics,Tablet,1,20000,15-06-2024,5.0,Paid,20000,Normal order
7,1008,Karan,Surat,Clothing,Jeans,4,3000,01-08-2024,3.0,Pending,12000,Normal order
8,1009,Mohit,Delhi,Furniture,Table,2,9000,10-09-2024,10.0,Pending,18000,Normal order
9,1010,Anjali,Mumbai,Electronics,Laptop,3,55000,01-10-2024,8.0,Paid,165000,Big order

In [108]:
#Create order_size 
def order_size(x):
    if x >= 50000:
        return "Big order"
    else:
        return "Normal order"
data["Order_size"] = data["Total_Amount"].apply(order_size)

#Clean data

In [109]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status,Total_Amount,Order_size
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10-01-2024,10.0,Paid,110000,Big order
1,1002,Priya,Mumbai,Electronics,Mobile,5,15000,15-02-2024,5.0,Paid,75000,Big order
2,1003,Amit,Delhi,Furniture,Chair,3,7000,05-03-2024,0.0,Pending,21000,Normal order
3,1004,Unknown,Surat,Clothing,Shirt,3,2500,05-03-2024,0.0,Paid,7500,Normal order
4,1005,Neha,Unknwon,Grocery,Rice,10,80,20-05-2024,2.0,Unknown,800,Normal order
5,1006,Neha,Ahmedabad,Electronics,Tablet,1,20000,15-06-2024,5.0,Paid,20000,Normal order
7,1008,Karan,Surat,Clothing,Jeans,4,3000,01-08-2024,3.0,Pending,12000,Normal order
8,1009,Mohit,Delhi,Furniture,Table,2,9000,10-09-2024,10.0,Pending,18000,Normal order
9,1010,Anjali,Mumbai,Electronics,Laptop,3,55000,01-10-2024,8.0,Paid,165000,Big order