In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\Sales_Pandas_Practice_Dataset.csv")

In [5]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2.0,55000,2024-01-10,10.0,paid
1,1002,PRIYA,MUMBAI,electronics,Mobile,5.0,15000,15/02/2024,5.0,PAID
2,1003,Amit,Delhi,Furniture,Chair,3.0,7000,2024-03-05,NaN,pending
3,1004,NaN,Surat,Clothing,Shirt,NaN,2500,NaN,0.0,Paid
4,1005,Neha,NaN,Grocery,Rice,10.0,80,2024-05-20,2.0,NaN
5,1006,Neha,Ahmedabad,NaN,Tablet,1.0,20000,2024-06-15,5.0,paid
6,1006,Neha,Ahmedabad,Electronics,Tablet,1.0,20000,2024-06-15,5.0,paid
7,1008,Karan,SURAT,Clothing,Jeans,4.0,3000,01-08-2024,3.0,pending
8,1009,MOHIT,Delhi,FURNITURE,Table,2.0,9000,2024/09/10,10.0,PENDING
9,1010,Anjali,Mumbai,Electronics,Laptop,3.0,55000,2024-10-01,8.0,paid

#Chack Besic EDA

In [6]:
#Chack the shape of the date set 
data.shape    #10 rows and 10 columns

(10, 10)

In [7]:
#Chack columns name 
data.columns

Index(['Order_ID', 'Customer', 'City', 'Category', 'Product', 'Quantity',
       'Price', 'Order_Date', 'Discount', 'Payment_Status'],
      dtype='object')

In [8]:
#Chack besic information of the data set 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10 non-null     int64
 1   Customer        9 non-null      object
 2   City            9 non-null      object
 3   Category        9 non-null      object
 4   Product         10 non-null     object
 5   Quantity        9 non-null      float64
 6   Price           10 non-null     int64
 7   Order_Date      9 non-null      object
 8   Discount        9 non-null      float64
 9   Payment_Status  9 non-null      object
dtypes: float64(2), int64(2), object(6)
memory usage: 932.0+ bytes

In [9]:
#Chack besic numeric calculation 
data.describe()

          Order_ID   Quantity        Price   Discount
count    10.000000   9.000000     10.00000   9.000000
mean   1005.400000   3.444444  18658.00000   5.333333
std       2.988868   2.788867  20382.58178   3.464102
min    1001.000000   1.000000     80.00000   0.000000
25%    1003.250000   2.000000   4000.00000   3.000000
50%    1005.500000   3.000000  12000.00000   5.000000
75%    1007.500000   4.000000  20000.00000   8.000000
max    1010.000000  10.000000  55000.00000  10.000000

In [10]:
#Find missing values in every columns 
data.isnull().sum()

Order_ID          0
Customer          1
City              1
Category          1
Product           0
Quantity          1
Price             0
Order_Date        1
Discount          1
Payment_Status    1
dtype: int64

#Handle all missing value

In [11]:
#Fill customer missing value 
data["Customer"] = data["Customer"].fillna("Unknown")

In [12]:
#Fill missing city name 
data["City"] = data["City"].fillna("Unknwon")

In [13]:
#Fill most frequent value of  missing Category 
data["Category"].value_counts()

Category
Electronics    3
Clothing       2
electronics    1
Furniture      1
Grocery        1
FURNITURE      1
Name: count, dtype: int64

In [14]:
data["Category"] = data["Category"].fillna(data["Category"].mode()[0])

In [15]:
#fill missing quantity value 
data["Quantity"] = data["Quantity"].fillna(data["Quantity"].median())

In [16]:
#Fill missing discount value 
data["Discount"] = data["Discount"].fillna(0)

In [17]:
#Fill missing date 
data["Order_Date"] = data["Order_Date"].ffill()

In [18]:
#Fill missing Payment_status 
data["Payment_Status"] = data["Payment_Status"].fillna("Unknown")

In [19]:
#Chack all missing value 
data.isnull().sum()   #All missing value fill

Order_ID          0
Customer          0
City              0
Category          0
Product           0
Quantity          0
Price             0
Order_Date        0
Discount          0
Payment_Status    0
dtype: int64

In [20]:
#Remove duplicate data 
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [21]:
#Drop duplicate value 
data = data.drop_duplicates().copy()

In [22]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2.0,55000,2024-01-10,10.0,paid
1,1002,PRIYA,MUMBAI,electronics,Mobile,5.0,15000,15/02/2024,5.0,PAID
2,1003,Amit,Delhi,Furniture,Chair,3.0,7000,2024-03-05,0.0,pending
3,1004,Unknown,Surat,Clothing,Shirt,3.0,2500,2024-03-05,0.0,Paid
4,1005,Neha,Unknwon,Grocery,Rice,10.0,80,2024-05-20,2.0,Unknown
5,1006,Neha,Ahmedabad,Electronics,Tablet,1.0,20000,2024-06-15,5.0,paid
7,1008,Karan,SURAT,Clothing,Jeans,4.0,3000,01-08-2024,3.0,pending
8,1009,MOHIT,Delhi,FURNITURE,Table,2.0,9000,2024/09/10,10.0,PENDING
9,1010,Anjali,Mumbai,Electronics,Laptop,3.0,55000,2024-10-01,8.0,paid

#Remove extra spaces from text columns

In [23]:
#Remove customer columns extra space 
data["Customer"] = data["Customer"].str.strip()

In [24]:
#Remove City columns extra space 
data["City"] = data["City"].str.strip()

In [25]:
#Remove Category columns extra space 
data["Category"] = data["Category"].str.strip()

In [26]:
#Remove customer columns extra space 
data["Product"] = data["Product"].str.strip()

In [27]:
#Remove Payment_Status columns extra space 
data["Payment_Status"] = data["Payment_Status"].str.strip()

#Convert text columns into proper format

In [28]:
#Customer name columns convert title case
data["Customer"] = data["Customer"].str.title()

In [29]:
#City name columns convert title case
data["City"] = data["City"].str.title()

In [30]:
#Category name columns convert title case 
data["Category"] = data["Category"].str.title()

#Date clean and convert propar date

In [31]:
data["Order_Date"] = pd.to_datetime(data["Order_Date"],format="mixed",dayfirst=True).dt.strftime("%d-%m-%Y")

In [32]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2.0,55000,10-01-2024,10.0,paid
1,1002,Priya,Mumbai,Electronics,Mobile,5.0,15000,15-02-2024,5.0,PAID
2,1003,Amit,Delhi,Furniture,Chair,3.0,7000,05-03-2024,0.0,pending
3,1004,Unknown,Surat,Clothing,Shirt,3.0,2500,05-03-2024,0.0,Paid
4,1005,Neha,Unknwon,Grocery,Rice,10.0,80,20-05-2024,2.0,Unknown
5,1006,Neha,Ahmedabad,Electronics,Tablet,1.0,20000,15-06-2024,5.0,paid
7,1008,Karan,Surat,Clothing,Jeans,4.0,3000,01-08-2024,3.0,pending
8,1009,Mohit,Delhi,Furniture,Table,2.0,9000,10-09-2024,10.0,PENDING
9,1010,Anjali,Mumbai,Electronics,Laptop,3.0,55000,01-10-2024,8.0,paid

In [33]:
#Quentity column  convert integer form
data["Quantity"] = data["Quantity"].astype(int)

In [34]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10-01-2024,10.0,paid
1,1002,Priya,Mumbai,Electronics,Mobile,5,15000,15-02-2024,5.0,PAID
2,1003,Amit,Delhi,Furniture,Chair,3,7000,05-03-2024,0.0,pending
3,1004,Unknown,Surat,Clothing,Shirt,3,2500,05-03-2024,0.0,Paid
4,1005,Neha,Unknwon,Grocery,Rice,10,80,20-05-2024,2.0,Unknown
5,1006,Neha,Ahmedabad,Electronics,Tablet,1,20000,15-06-2024,5.0,paid
7,1008,Karan,Surat,Clothing,Jeans,4,3000,01-08-2024,3.0,pending
8,1009,Mohit,Delhi,Furniture,Table,2,9000,10-09-2024,10.0,PENDING
9,1010,Anjali,Mumbai,Electronics,Laptop,3,55000,01-10-2024,8.0,paid

In [35]:
#Create total amount column
data["Total_Amount"] = data["Price"] * data["Quantity"]
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status,Total_Amount
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10-01-2024,10.0,paid,110000
1,1002,Priya,Mumbai,Electronics,Mobile,5,15000,15-02-2024,5.0,PAID,75000
2,1003,Amit,Delhi,Furniture,Chair,3,7000,05-03-2024,0.0,pending,21000
3,1004,Unknown,Surat,Clothing,Shirt,3,2500,05-03-2024,0.0,Paid,7500
4,1005,Neha,Unknwon,Grocery,Rice,10,80,20-05-2024,2.0,Unknown,800
5,1006,Neha,Ahmedabad,Electronics,Tablet,1,20000,15-06-2024,5.0,paid,20000
7,1008,Karan,Surat,Clothing,Jeans,4,3000,01-08-2024,3.0,pending,12000
8,1009,Mohit,Delhi,Furniture,Table,2,9000,10-09-2024,10.0,PENDING,18000
9,1010,Anjali,Mumbai,Electronics,Laptop,3,55000,01-10-2024,8.0,paid,165000

In [36]:
#Create order_size 
def order_size(x):
    if x >= 50000:
        return "Big order"
    else:
        return "Normal order"
data["Order_size"] = data["Total_Amount"].apply(order_size)

#Clean data

In [37]:
data

,Order_ID,Customer,City,Category,Product,Quantity,Price,Order_Date,Discount,Payment_Status,Total_Amount,Order_size
0,1001,Rahul,Ahmedabad,Electronics,Laptop,2,55000,10-01-2024,10.0,paid,110000,Big order
1,1002,Priya,Mumbai,Electronics,Mobile,5,15000,15-02-2024,5.0,PAID,75000,Big order
2,1003,Amit,Delhi,Furniture,Chair,3,7000,05-03-2024,0.0,pending,21000,Normal order
3,1004,Unknown,Surat,Clothing,Shirt,3,2500,05-03-2024,0.0,Paid,7500,Normal order
4,1005,Neha,Unknwon,Grocery,Rice,10,80,20-05-2024,2.0,Unknown,800,Normal order
5,1006,Neha,Ahmedabad,Electronics,Tablet,1,20000,15-06-2024,5.0,paid,20000,Normal order
7,1008,Karan,Surat,Clothing,Jeans,4,3000,01-08-2024,3.0,pending,12000,Normal order
8,1009,Mohit,Delhi,Furniture,Table,2,9000,10-09-2024,10.0,PENDING,18000,Normal order
9,1010,Anjali,Mumbai,Electronics,Laptop,3,55000,01-10-2024,8.0,paid,165000,Big order

#Kaggle  iris data set practice

In [2]:
data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\Iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

#Chack EDA (Exploratory data analysis)

In [4]:
#Chack first 5 rows  and last 5 rows 
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
data.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
#Chack besic statistical summary 
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
#Chack how many rows and columns 
data.shape            #150 rows and 6 columns

(150, 6)

In [8]:
#Chack missing value 
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [9]:
#Chack petallengthcm max and min 
data["PetalLengthCm"].max()

6.9

In [10]:
data["PetalLengthCm"].min()

1.0

#Data selecting and filtering

In [11]:
#Select only Sepallengthcm and Petallengthcm
data[["SepalLengthCm","PetalLengthCm"]]

     SepalLengthCm  PetalLengthCm
0              5.1            1.4
1              4.9            1.4
2              4.7            1.3
3              4.6            1.5
4              5.0            1.4
..             ...            ...
145            6.7            5.2
146            6.3            5.0
147            6.5            5.2
148            6.2            5.4
149            5.9            5.1

[150 rows x 2 columns]

In [12]:
#Select all rows where species is iris-setosa
data[data["Species"] == "Iris-setosa"]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [13]:
#Select rows where speallengthcm is about 5.5
data[data["SepalLengthCm"] >= 5.5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
36,37,5.5,3.5,1.3,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [14]:
#select rows with index 20 to 30 and columns sepalwidthcm and petalwidthcm
data.loc[20:30,["SepalWidthCm","PetalWidthCm"]]

    SepalWidthCm  PetalWidthCm
20           3.4           0.2
21           3.7           0.4
22           3.6           0.2
23           3.3           0.5
24           3.4           0.2
25           3.0           0.2
26           3.4           0.4
27           3.5           0.2
28           3.4           0.2
29           3.2           0.2
30           3.1           0.2

In [15]:
#Select the first 15 rows and first 3 columns 
data.iloc[0:16,0:3]

    Id  SepalLengthCm  SepalWidthCm
0    1            5.1           3.5
1    2            4.9           3.0
2    3            4.7           3.2
3    4            4.6           3.1
4    5            5.0           3.6
5    6            5.4           3.9
6    7            4.6           3.4
7    8            5.0           3.4
8    9            4.4           2.9
9   10            4.9           3.1
10  11            5.4           3.7
11  12            4.8           3.4
12  13            4.8           3.0
13  14            4.3           3.0
14  15            5.8           4.0
15  16            5.7           4.4

In [16]:
#Filter rows where species  is iris-versicolor and iris-virginica 
data[(data["Species"] == "Iris-virginica") | (data["Species"] == "Iris - Versicolor")]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [17]:
#Select rows where petallengthcm about 4 
data.query("PetalLengthCm >= 4")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [18]:
#Select rows where Sepallengthcm about 5 and Species = 'iris-setosa'
data.query("SepalLengthCm >= 5 and Species == 'Iris-setosa'")

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [19]:
#With a variable x = 1.5 to filter rows where petallengthcm about x 
x = 1.5
data.query("PetalLengthCm > @x")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
5,6,5.4,3.9,1.7,0.4,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

#Data Cleanning and preprocessing

In [20]:
#Chack duplicate rows and columns 
data.duplicated().sum()

np.int64(0)

In [21]:
#Rename Sepallengthcm and Petallengthcm
data.rename(columns={"SepalLengthCm":"Sepal_Length","PetalLengthCm":"Patel_Length"})

,Id,Sepal_Length,SepalWidthCm,Patel_Length,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [24]:
#Convert the species column to categorycal data type 
data["Species"] = pd.Categorical(data["Species"])
print(data["Species"].dtype)

category

In [27]:
#Reset the index of the data frame after filtering rows for 'iris-setosa' only 
data.query("Species == 'Iris-setosa'").reset_index(drop=True)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

#use string method

In [30]:
#Convert Species columns to uppercase 
data["Species"].str.upper()

0         IRIS-SETOSA
1         IRIS-SETOSA
2         IRIS-SETOSA
3         IRIS-SETOSA
4         IRIS-SETOSA
            ...
145    IRIS-VIRGINICA
146    IRIS-VIRGINICA
147    IRIS-VIRGINICA
148    IRIS-VIRGINICA
149    IRIS-VIRGINICA
Name: Species, Length: 150, dtype: object

In [33]:
#Remove the  'Iris' from the species column
data["Species"].str.replace("Iris-","")

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object

In [35]:
#Chack how many species names contain the letter 'v'
data["Species"].str.contains('v',case=False).sum()

np.int64(100)

In [41]:
#Find the lenght of each 'Species'
data["Species"].str.len()

0      11
1      11
2      11
3      11
4      11
       ..
145    14
146    14
147    14
148    14
149    14
Name: Species, Length: 150, dtype: int64

In [49]:
data["Species"].str.split('-')

0         [Iris, setosa]
1         [Iris, setosa]
2         [Iris, setosa]
3         [Iris, setosa]
4         [Iris, setosa]
             ...
145    [Iris, virginica]
146    [Iris, virginica]
147    [Iris, virginica]
148    [Iris, virginica]
149    [Iris, virginica]
Name: Species, Length: 150, dtype: object

In [51]:
#Create new columns Spealarea 
data["SpealArea"] = data["SepalLengthCm"] * data["SepalWidthCm"]
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,SpealArea
0,1,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,2,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,3,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5,5.0,3.6,1.4,0.2,Iris-setosa,18.00
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,20.10
146,147,6.3,2.5,5.0,1.9,Iris-virginica,15.75
147,148,6.5,3.0,5.2,2.0,Iris-virginica,19.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,21.08
149,150,5.9,3.0,5.1,1.8,Iris-virginica,17.70

In [67]:
#Create petallengthcm acoding large and small flower 
def labels(x):
    if x >= 4:
        return "Large"
    else:
        return "Small"
data["Labels_PetalLength"] = data["PetalLengthCm"].apply(labels)
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,SpealArea,Labels_PetalLength
0,1,5.1,3.5,1.4,0.2,Iris-setosa,17.85,Small
1,2,4.9,3.0,1.4,0.2,Iris-setosa,14.70,Small
2,3,4.7,3.2,1.3,0.2,Iris-setosa,15.04,Small
3,4,4.6,3.1,1.5,0.2,Iris-setosa,14.26,Small
4,5,5.0,3.6,1.4,0.2,Iris-setosa,18.00,Small
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,20.10,Large
146,147,6.3,2.5,5.0,1.9,Iris-virginica,15.75,Large
147,148,6.5,3.0,5.2,2.0,Iris-virginica,19.50,Large
148,149,6.2,3.4,5.4,2.3,Iris-virginica,21.08,Large
149,150,5.9,3.0,5.1,1.8,Iris-virginica,17.70,Large